//! Ray queries: the inline ray-tracing surface WGSL exposes.
//!
//! Naga supplies the two struct types involved — `RayDesc` for what to trace
//! and `RayIntersection` for what was found — so they are generated on demand
//! rather than declared here, and their field names come from Naga.
//!
//! A query is a local the operations act on, as methods: `rq.proceed()`.

use naga::{Block, Expression, Function, Handle, RayQueryFunction, Scalar, Statement, Type};
use syn::Expr;

use super::emit::emit;
use super::env::Env;
use super::place::Place;
use super::{Context, Typed};
use crate::Error;

/// `acceleration_structure` and `ray_query`, which take no type arguments.
pub(super) fn parse_ray_type(ctx: &mut Context, name: &str) -> Option<Handle<Type>> {
    let inner = match name {
        "acceleration_structure" => naga::TypeInner::AccelerationStructure {
            vertex_return: false,
        },
        "ray_query" => naga::TypeInner::RayQuery {
            vertex_return: false,
        },
        _ => return None,
    };
    Some(ctx.intern_handle_type(inner))
}

/// `RayDesc` and `RayIntersection`, generated by Naga the first time they are
/// named so that their layout matches what the backends expect.
pub(super) fn special_struct(ctx: &mut Context, name: &str) -> Option<Handle<Type>> {
    match name {
        "RayDesc" => Some(ctx.module.generate_ray_desc_type()),
        "RayIntersection" => Some(ctx.module.generate_ray_intersection_type()),
        _ => None,
    }
}

/// `RayFlag` and `RayQueryIntersection`: a set and an enum in Rust, and the
/// `u32` that Naga's `RayDesc` and `RayIntersection` hold on the GPU.
pub(super) fn is_ray_word_type(name: &str) -> bool {
    matches!(name, "RayFlag" | "RayQueryIntersection")
}

/// `RayFlag::CULL_NO_OPAQUE` and `RayQueryIntersection::None`: a flag or a
/// kind, by the name `synaga_shader` gives it.
pub(super) fn typed_const(ty: &str, name: &str) -> Option<u32> {
    use naga::{RayFlag, RayQueryIntersection as Kind};
    let value = match (ty, name) {
        ("RayFlag", "FORCE_OPAQUE") => RayFlag::FORCE_OPAQUE.bits(),
        ("RayFlag", "FORCE_NO_OPAQUE") => RayFlag::FORCE_NO_OPAQUE.bits(),
        ("RayFlag", "TERMINATE_ON_FIRST_HIT") => RayFlag::TERMINATE_ON_FIRST_HIT.bits(),
        ("RayFlag", "SKIP_CLOSEST_HIT_SHADER") => RayFlag::SKIP_CLOSEST_HIT_SHADER.bits(),
        ("RayFlag", "CULL_BACK_FACING") => RayFlag::CULL_BACK_FACING.bits(),
        ("RayFlag", "CULL_FRONT_FACING") => RayFlag::CULL_FRONT_FACING.bits(),
        ("RayFlag", "CULL_OPAQUE") => RayFlag::CULL_OPAQUE.bits(),
        ("RayFlag", "CULL_NO_OPAQUE") => RayFlag::CULL_NO_OPAQUE.bits(),
        ("RayFlag", "SKIP_TRIANGLES") => RayFlag::SKIP_TRIANGLES.bits(),
        ("RayFlag", "SKIP_AABBS") => RayFlag::SKIP_AABBS.bits(),
        ("RayQueryIntersection", "None") => Kind::None as u32,
        ("RayQueryIntersection", "Triangle") => Kind::Triangle as u32,
        ("RayQueryIntersection", "Generated") => Kind::Generated as u32,
        ("RayQueryIntersection", "Aabb") => Kind::Aabb as u32,
        _ => return None,
    };
    Some(value)
}

/// `RayFlag::empty()` and `RayFlag::all()`, which `bitflags!` gives the set.
pub(super) fn flags_call(ty: &str, name: &str) -> Option<u32> {
    match (ty, name) {
        ("RayFlag", "empty") => Some(0),
        ("RayFlag", "all") => Some(naga::RayFlag::all().bits()),
        _ => None,
    }
}

/// The predeclared ray flags and intersection kinds, which WGSL provides as
/// bare names rather than as constants anyone declares.
pub(super) fn predeclared_const(name: &str) -> Option<u32> {
    use naga::RayFlag;
    let value = match name {
        "RAY_FLAG_NONE" => RayFlag::empty().bits(),
        "RAY_FLAG_FORCE_OPAQUE" => RayFlag::FORCE_OPAQUE.bits(),
        "RAY_FLAG_FORCE_NO_OPAQUE" => RayFlag::FORCE_NO_OPAQUE.bits(),
        "RAY_FLAG_TERMINATE_ON_FIRST_HIT" => RayFlag::TERMINATE_ON_FIRST_HIT.bits(),
        "RAY_FLAG_SKIP_CLOSEST_HIT_SHADER" => RayFlag::SKIP_CLOSEST_HIT_SHADER.bits(),
        "RAY_FLAG_CULL_BACK_FACING" => RayFlag::CULL_BACK_FACING.bits(),
        "RAY_FLAG_CULL_FRONT_FACING" => RayFlag::CULL_FRONT_FACING.bits(),
        "RAY_FLAG_CULL_OPAQUE" => RayFlag::CULL_OPAQUE.bits(),
        "RAY_FLAG_CULL_NO_OPAQUE" => RayFlag::CULL_NO_OPAQUE.bits(),
        "RAY_FLAG_SKIP_TRIANGLES" => RayFlag::SKIP_TRIANGLES.bits(),
        "RAY_FLAG_SKIP_AABBS" => RayFlag::SKIP_AABBS.bits(),
        "RAY_QUERY_INTERSECTION_NONE" => naga::RayQueryIntersection::None as u32,
        "RAY_QUERY_INTERSECTION_TRIANGLE" => naga::RayQueryIntersection::Triangle as u32,
        "RAY_QUERY_INTERSECTION_GENERATED" => naga::RayQueryIntersection::Generated as u32,
        "RAY_QUERY_INTERSECTION_AABB" => naga::RayQueryIntersection::Aabb as u32,
        _ => return None,
    };
    Some(value)
}

/// `rq.proceed()` and the rest, on the ray query `place` names.
///
/// A query is storage the operations change, so the receiver is a place: the
/// local it was declared as.
pub(super) fn lower_ray_method(
    ctx: &mut Context,
    function: &mut Function,
    body: &mut Block,
    place: Place,
    name: &str,
    args: &[&Expr],
    env: &mut Env,
) -> Result<Option<Typed>, Error> {
    let query = place.pointer;
    let fun = match (name, args) {
        ("initialize", [scene, desc]) => {
            let (acceleration_structure, acc_ty) =
                super::expr::lower_expr(ctx, function, body, scene, env)?;
            if !matches!(
                ctx.module.types[acc_ty].inner,
                naga::TypeInner::AccelerationStructure { .. }
            ) {
                return Err(Error::NotAnAccelerationStructure(name.into()));
            }
            let (descriptor, _) = super::expr::lower_expr(ctx, function, body, desc, env)?;
            RayQueryFunction::Initialize {
                acceleration_structure,
                descriptor,
            }
        }
        ("generate_intersection", [hit_t]) => {
            let (hit_t, _) = super::expr::lower_expr(ctx, function, body, hit_t, env)?;
            RayQueryFunction::GenerateIntersection { hit_t }
        }
        ("confirm_intersection", []) => RayQueryFunction::ConfirmIntersection,
        ("terminate", []) => RayQueryFunction::Terminate,
        ("proceed", []) => {
            // The result is its own expression kind, not an emitted one.
            let result = function
                .expressions
                .append(Expression::RayQueryProceedResult, ctx.span);
            body.push(
                Statement::RayQuery {
                    query,
                    fun: RayQueryFunction::Proceed { result },
                },
                ctx.span,
            );
            return Ok(Some((result, ctx.intern_scalar(Scalar::BOOL))));
        }
        ("committed_intersection" | "candidate_intersection", []) => {
            let ty = ctx.module.generate_ray_intersection_type();
            let handle = emit(
                ctx,
                function,
                body,
                Expression::RayQueryGetIntersection {
                    query,
                    committed: name == "committed_intersection",
                },
            )?;
            return Ok(Some((handle, ty)));
        }
        (
            "initialize"
            | "generate_intersection"
            | "confirm_intersection"
            | "terminate"
            | "proceed"
            | "committed_intersection"
            | "candidate_intersection",
            _,
        ) => return Err(Error::WrongArgCount(name.into())),
        _ => return Err(Error::UnsupportedMethod(format!("{name} on a ray query"))),
    };

    body.push(Statement::RayQuery { query, fun }, ctx.span);
    Ok(None)
}

/// Does a method with this name drive a ray query? A query it is called on has
/// to live in a local, since the operation changes it.
pub(super) fn is_ray_method(name: &str) -> bool {
    matches!(
        name,
        "initialize"
            | "proceed"
            | "generate_intersection"
            | "confirm_intersection"
            | "terminate"
            | "committed_intersection"
            | "candidate_intersection"
    )
}
