//! Vector types.
//!
//! Generated by `generate_vector.py`, then `cargo fmt`; edit that, not this.
//!
//! `Vec3<T>` is WGSL's `vec3<T>`, and a bare `Vec3` is `Vec3<f32>`, as `vec3f`
//! is. `vec3(x, y, z)` builds one of whatever its components are:
//! `vec3(0.0, 1.0, 0.0)` is a `Vec3<f32>` and `vec3(1, 2, 3)` a `Vec3<i32>`, as
//! WGSL's literals go, and `vec3::<u32>(1, 2, 3)` says which outright:
//!
//! ```
//! use synaga_shader::*;
//!
//! let up = vec3(0.0, 1.0, 0.0);
//! let cell = vec2(3, 4);
//! let size = vec2::<u32>(640, 480);
//! # use core::any::{type_name, type_name_of_val as of};
//! # assert_eq!(of(&up), type_name::<Vec3<f32>>());
//! # assert_eq!(of(&cell), type_name::<Vec2<i32>>());
//! # assert_eq!(of(&size), type_name::<Vec2<u32>>());
//! ```
//!
//! Component access splits two ways: a single `x`/`y`/`z`/`w` is a field, so
//! `v.x` reads and `v.x = 1.0` writes, while every other swizzle is a method.
//! Rust has no way to give one piece of memory a hundred overlapping names, so
//! `v.xyz` has to be `v.xyz()`; `.r`/`.g`/`.b`/`.a` are methods for the same
//! reason, since they would alias the `x`/`y`/`z`/`w` fields.
//!
//! Comparisons are methods too. `a < b` in a shader yields one bool per lane,
//! and Rust's `PartialOrd` yields a single `bool`, so the lane-wise forms are
//! spelled `cmplt`, `cmple`, and so on, as glam spells them.

use core::ops::*;

use crate::unimplemented_on_cpu;

/// What a vector's lanes hold: `f32`, `i32`, `u32` or `bool`.
///
/// The bound is also what makes `vec3(0.0, 1.0, 0.0)` a `Vec3<f32>`: `f32` is
/// the one float type that is a `Scalar`, so Rust gives the literals that type
/// rather than its usual `f64`.
pub trait Scalar: Copy + sealed::Sealed {
    /// Zero, or `false`.
    const ZERO: Self;
    /// One, or `true`.
    const ONE: Self;
}

mod sealed {
    pub trait Sealed {}
    impl Sealed for f32 {}
    impl Sealed for i32 {}
    impl Sealed for u32 {}
    impl Sealed for bool {}
}

impl Scalar for f32 {
    const ZERO: Self = 0.0;
    const ONE: Self = 1.0;
}
impl Scalar for i32 {
    const ZERO: Self = 0;
    const ONE: Self = 1;
}
impl Scalar for u32 {
    const ZERO: Self = 0;
    const ONE: Self = 1;
}
impl Scalar for bool {
    const ZERO: Self = false;
    const ONE: Self = true;
}

/// The operators every vector has, and the ones only some do.
///
/// `macro_rules!` cannot paste `Add` and `Assign` into one identifier, so each
/// operator names its assigning form too. `$shift` is the `VecN<u32>` a
/// lane-wise shift takes, since WGSL wants an unsigned shift amount whatever
/// is shifted.
macro_rules! vector_ops {
    ($name:ty, $scalar:ty, $shift:ty $(, $group:ident)*) => {
        $(vector_ops!(@group $group, $name, $scalar, $shift);)*
    };

    (@group arith, $name:ty, $scalar:ty, $shift:ty) => {
        vector_ops!(@scalar_too Add, add, AddAssign, add_assign, $name, $scalar);
        vector_ops!(@scalar_too Sub, sub, SubAssign, sub_assign, $name, $scalar);
        vector_ops!(@scalar_too Mul, mul, MulAssign, mul_assign, $name, $scalar);
        vector_ops!(@scalar_too Div, div, DivAssign, div_assign, $name, $scalar);
        vector_ops!(@scalar_too Rem, rem, RemAssign, rem_assign, $name, $scalar);
    };
    (@group bitwise, $name:ty, $scalar:ty, $shift:ty) => {
        vector_ops!(@lanewise BitAnd, bitand, BitAndAssign, bitand_assign, $name);
        vector_ops!(@lanewise BitOr, bitor, BitOrAssign, bitor_assign, $name);
        vector_ops!(@lanewise BitXor, bitxor, BitXorAssign, bitxor_assign, $name);
    };
    (@group shift, $name:ty, $scalar:ty, $shift:ty) => {
        vector_ops!(@shift Shl, shl, $name, $shift);
        vector_ops!(@shift Shr, shr, $name, $shift);
    };
    (@group neg, $name:ty, $scalar:ty, $shift:ty) => {
        impl Neg for $name {
            type Output = Self;
            #[inline]
            fn neg(self) -> Self { unimplemented_on_cpu() }
        }
    };
    (@group not, $name:ty, $scalar:ty, $shift:ty) => {
        impl Not for $name {
            type Output = Self;
            #[inline]
            fn not(self) -> Self { unimplemented_on_cpu() }
        }
    };

    // Arithmetic also works against a scalar, from either side: a shader
    // writes both `v * 2.0` and `2.0 * v`.
    (@scalar_too $trait:ident, $method:ident, $assign:ident, $assign_fn:ident,
     $name:ty, $scalar:ty) => {
        vector_ops!(@lanewise $trait, $method, $assign, $assign_fn, $name);
        impl $trait<$scalar> for $name {
            type Output = Self;
            #[inline]
            fn $method(self, rhs: $scalar) -> Self { unimplemented_on_cpu() }
        }
        impl $trait<$name> for $scalar {
            type Output = $name;
            #[inline]
            fn $method(self, rhs: $name) -> $name { unimplemented_on_cpu() }
        }
        impl $assign<$scalar> for $name {
            #[inline]
            fn $assign_fn(&mut self, rhs: $scalar) { unimplemented_on_cpu() }
        }
    };
    (@lanewise $trait:ident, $method:ident, $assign:ident, $assign_fn:ident, $name:ty) => {
        impl $trait for $name {
            type Output = Self;
            #[inline]
            fn $method(self, rhs: Self) -> Self { unimplemented_on_cpu() }
        }
        impl $assign for $name {
            #[inline]
            fn $assign_fn(&mut self, rhs: Self) { unimplemented_on_cpu() }
        }
    };
    (@shift $trait:ident, $method:ident, $name:ty, $shift:ty) => {
        impl $trait<$shift> for $name {
            type Output = Self;
            #[inline]
            fn $method(self, rhs: $shift) -> Self { unimplemented_on_cpu() }
        }
        impl $trait<u32> for $name {
            type Output = Self;
            #[inline]
            fn $method(self, rhs: u32) -> Self { unimplemented_on_cpu() }
        }
    };
}

/// `vec2<T>` in WGSL. A bare `Vec2` is `Vec2<f32>`, WGSL's `vec2f`.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
#[repr(C)]
pub struct Vec2<T = f32> {
    pub x: T,
    pub y: T,
}

/// Build a [`Vec2`] from its components.
#[inline]
pub const fn vec2<T: Scalar>(x: T, y: T) -> Vec2<T> {
    Vec2 { x, y }
}

impl<T: Scalar> Vec2<T> {
    pub const ZERO: Self = vec2(T::ZERO, T::ZERO);
    pub const ONE: Self = vec2(T::ONE, T::ONE);

    /// Every lane set to `v`.
    #[inline]
    pub const fn splat(v: T) -> Self {
        vec2(v, v)
    }

    /// One lane wider, with `z` appended. This is how a shader's
    /// `vec3(v, z)` is spelled.
    #[inline]
    pub const fn extend(self, z: T) -> Vec3<T> {
        vec3(self.x, self.y, z)
    }

    /// Lane-wise `==`.
    #[inline]
    pub fn cmpeq(self, rhs: Self) -> Vec2<bool> {
        unimplemented_on_cpu()
    }

    /// Lane-wise `!=`.
    #[inline]
    pub fn cmpne(self, rhs: Self) -> Vec2<bool> {
        unimplemented_on_cpu()
    }

    #[inline]
    pub const fn xy(self) -> Vec2<T> {
        vec2(self.x, self.y)
    }

    #[inline]
    pub const fn yx(self) -> Vec2<T> {
        vec2(self.y, self.x)
    }

    #[inline]
    pub const fn r(self) -> T {
        self.x
    }

    #[inline]
    pub const fn g(self) -> T {
        self.y
    }

    #[inline]
    pub const fn rg(self) -> Vec2<T> {
        vec2(self.x, self.y)
    }

    #[inline]
    pub const fn gr(self) -> Vec2<T> {
        vec2(self.y, self.x)
    }
}

impl<T: Scalar> Index<usize> for Vec2<T> {
    type Output = T;
    #[inline]
    fn index(&self, index: usize) -> &T {
        unimplemented_on_cpu()
    }
}
impl<T: Scalar> IndexMut<usize> for Vec2<T> {
    #[inline]
    fn index_mut(&mut self, index: usize) -> &mut T {
        unimplemented_on_cpu()
    }
}

impl Vec2<f32> {
    /// Lane-wise `<`.
    #[inline]
    pub fn cmplt(self, rhs: Self) -> Vec2<bool> {
        unimplemented_on_cpu()
    }

    /// Lane-wise `<=`.
    #[inline]
    pub fn cmple(self, rhs: Self) -> Vec2<bool> {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>`.
    #[inline]
    pub fn cmpgt(self, rhs: Self) -> Vec2<bool> {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>=`.
    #[inline]
    pub fn cmpge(self, rhs: Self) -> Vec2<bool> {
        unimplemented_on_cpu()
    }
}
vector_ops!(Vec2<f32>, f32, Vec2<u32>, arith, neg);

impl Vec2<i32> {
    /// Lane-wise `<`.
    #[inline]
    pub fn cmplt(self, rhs: Self) -> Vec2<bool> {
        unimplemented_on_cpu()
    }

    /// Lane-wise `<=`.
    #[inline]
    pub fn cmple(self, rhs: Self) -> Vec2<bool> {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>`.
    #[inline]
    pub fn cmpgt(self, rhs: Self) -> Vec2<bool> {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>=`.
    #[inline]
    pub fn cmpge(self, rhs: Self) -> Vec2<bool> {
        unimplemented_on_cpu()
    }
}
vector_ops!(Vec2<i32>, i32, Vec2<u32>, arith, bitwise, shift, neg, not);

impl Vec2<u32> {
    /// Lane-wise `<`.
    #[inline]
    pub fn cmplt(self, rhs: Self) -> Vec2<bool> {
        unimplemented_on_cpu()
    }

    /// Lane-wise `<=`.
    #[inline]
    pub fn cmple(self, rhs: Self) -> Vec2<bool> {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>`.
    #[inline]
    pub fn cmpgt(self, rhs: Self) -> Vec2<bool> {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>=`.
    #[inline]
    pub fn cmpge(self, rhs: Self) -> Vec2<bool> {
        unimplemented_on_cpu()
    }
}
vector_ops!(Vec2<u32>, u32, Vec2<u32>, arith, bitwise, shift, not);

vector_ops!(Vec2<bool>, bool, Vec2<u32>, bitwise, not);

/// `vec3<T>` in WGSL. A bare `Vec3` is `Vec3<f32>`, WGSL's `vec3f`.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
#[repr(C)]
pub struct Vec3<T = f32> {
    pub x: T,
    pub y: T,
    pub z: T,
}

/// Build a [`Vec3`] from its components.
#[inline]
pub const fn vec3<T: Scalar>(x: T, y: T, z: T) -> Vec3<T> {
    Vec3 { x, y, z }
}

impl<T: Scalar> Vec3<T> {
    pub const ZERO: Self = vec3(T::ZERO, T::ZERO, T::ZERO);
    pub const ONE: Self = vec3(T::ONE, T::ONE, T::ONE);

    /// Every lane set to `v`.
    #[inline]
    pub const fn splat(v: T) -> Self {
        vec3(v, v, v)
    }

    /// One lane wider, with `w` appended. This is how a shader's
    /// `vec4(v, w)` is spelled.
    #[inline]
    pub const fn extend(self, w: T) -> Vec4<T> {
        vec4(self.x, self.y, self.z, w)
    }

    /// One lane narrower, dropping the last.
    #[inline]
    pub const fn truncate(self) -> Vec2<T> {
        vec2(self.x, self.y)
    }

    /// Lane-wise `==`.
    #[inline]
    pub fn cmpeq(self, rhs: Self) -> Vec3<bool> {
        unimplemented_on_cpu()
    }

    /// Lane-wise `!=`.
    #[inline]
    pub fn cmpne(self, rhs: Self) -> Vec3<bool> {
        unimplemented_on_cpu()
    }

    #[inline]
    pub const fn xy(self) -> Vec2<T> {
        vec2(self.x, self.y)
    }

    #[inline]
    pub const fn xz(self) -> Vec2<T> {
        vec2(self.x, self.z)
    }

    #[inline]
    pub const fn yx(self) -> Vec2<T> {
        vec2(self.y, self.x)
    }

    #[inline]
    pub const fn yz(self) -> Vec2<T> {
        vec2(self.y, self.z)
    }

    #[inline]
    pub const fn zx(self) -> Vec2<T> {
        vec2(self.z, self.x)
    }

    #[inline]
    pub const fn zy(self) -> Vec2<T> {
        vec2(self.z, self.y)
    }

    #[inline]
    pub const fn xyz(self) -> Vec3<T> {
        vec3(self.x, self.y, self.z)
    }

    #[inline]
    pub const fn xzy(self) -> Vec3<T> {
        vec3(self.x, self.z, self.y)
    }

    #[inline]
    pub const fn yxz(self) -> Vec3<T> {
        vec3(self.y, self.x, self.z)
    }

    #[inline]
    pub const fn yzx(self) -> Vec3<T> {
        vec3(self.y, self.z, self.x)
    }

    #[inline]
    pub const fn zxy(self) -> Vec3<T> {
        vec3(self.z, self.x, self.y)
    }

    #[inline]
    pub const fn zyx(self) -> Vec3<T> {
        vec3(self.z, self.y, self.x)
    }

    #[inline]
    pub const fn r(self) -> T {
        self.x
    }

    #[inline]
    pub const fn g(self) -> T {
        self.y
    }

    #[inline]
    pub const fn b(self) -> T {
        self.z
    }

    #[inline]
    pub const fn rg(self) -> Vec2<T> {
        vec2(self.x, self.y)
    }

    #[inline]
    pub const fn gr(self) -> Vec2<T> {
        vec2(self.y, self.x)
    }

    #[inline]
    pub const fn rgb(self) -> Vec3<T> {
        vec3(self.x, self.y, self.z)
    }
}

impl<T: Scalar> Index<usize> for Vec3<T> {
    type Output = T;
    #[inline]
    fn index(&self, index: usize) -> &T {
        unimplemented_on_cpu()
    }
}
impl<T: Scalar> IndexMut<usize> for Vec3<T> {
    #[inline]
    fn index_mut(&mut self, index: usize) -> &mut T {
        unimplemented_on_cpu()
    }
}

impl Vec3<f32> {
    /// Lane-wise `<`.
    #[inline]
    pub fn cmplt(self, rhs: Self) -> Vec3<bool> {
        unimplemented_on_cpu()
    }

    /// Lane-wise `<=`.
    #[inline]
    pub fn cmple(self, rhs: Self) -> Vec3<bool> {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>`.
    #[inline]
    pub fn cmpgt(self, rhs: Self) -> Vec3<bool> {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>=`.
    #[inline]
    pub fn cmpge(self, rhs: Self) -> Vec3<bool> {
        unimplemented_on_cpu()
    }
}
vector_ops!(Vec3<f32>, f32, Vec3<u32>, arith, neg);

impl Vec3<i32> {
    /// Lane-wise `<`.
    #[inline]
    pub fn cmplt(self, rhs: Self) -> Vec3<bool> {
        unimplemented_on_cpu()
    }

    /// Lane-wise `<=`.
    #[inline]
    pub fn cmple(self, rhs: Self) -> Vec3<bool> {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>`.
    #[inline]
    pub fn cmpgt(self, rhs: Self) -> Vec3<bool> {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>=`.
    #[inline]
    pub fn cmpge(self, rhs: Self) -> Vec3<bool> {
        unimplemented_on_cpu()
    }
}
vector_ops!(Vec3<i32>, i32, Vec3<u32>, arith, bitwise, shift, neg, not);

impl Vec3<u32> {
    /// Lane-wise `<`.
    #[inline]
    pub fn cmplt(self, rhs: Self) -> Vec3<bool> {
        unimplemented_on_cpu()
    }

    /// Lane-wise `<=`.
    #[inline]
    pub fn cmple(self, rhs: Self) -> Vec3<bool> {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>`.
    #[inline]
    pub fn cmpgt(self, rhs: Self) -> Vec3<bool> {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>=`.
    #[inline]
    pub fn cmpge(self, rhs: Self) -> Vec3<bool> {
        unimplemented_on_cpu()
    }
}
vector_ops!(Vec3<u32>, u32, Vec3<u32>, arith, bitwise, shift, not);

vector_ops!(Vec3<bool>, bool, Vec3<u32>, bitwise, not);

/// `vec4<T>` in WGSL. A bare `Vec4` is `Vec4<f32>`, WGSL's `vec4f`.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
#[repr(C)]
pub struct Vec4<T = f32> {
    pub x: T,
    pub y: T,
    pub z: T,
    pub w: T,
}

/// Build a [`Vec4`] from its components.
#[inline]
pub const fn vec4<T: Scalar>(x: T, y: T, z: T, w: T) -> Vec4<T> {
    Vec4 { x, y, z, w }
}

impl<T: Scalar> Vec4<T> {
    pub const ZERO: Self = vec4(T::ZERO, T::ZERO, T::ZERO, T::ZERO);
    pub const ONE: Self = vec4(T::ONE, T::ONE, T::ONE, T::ONE);

    /// Every lane set to `v`.
    #[inline]
    pub const fn splat(v: T) -> Self {
        vec4(v, v, v, v)
    }

    /// One lane narrower, dropping the last.
    #[inline]
    pub const fn truncate(self) -> Vec3<T> {
        vec3(self.x, self.y, self.z)
    }

    /// Lane-wise `==`.
    #[inline]
    pub fn cmpeq(self, rhs: Self) -> Vec4<bool> {
        unimplemented_on_cpu()
    }

    /// Lane-wise `!=`.
    #[inline]
    pub fn cmpne(self, rhs: Self) -> Vec4<bool> {
        unimplemented_on_cpu()
    }

    #[inline]
    pub const fn xy(self) -> Vec2<T> {
        vec2(self.x, self.y)
    }

    #[inline]
    pub const fn xz(self) -> Vec2<T> {
        vec2(self.x, self.z)
    }

    #[inline]
    pub const fn xw(self) -> Vec2<T> {
        vec2(self.x, self.w)
    }

    #[inline]
    pub const fn yx(self) -> Vec2<T> {
        vec2(self.y, self.x)
    }

    #[inline]
    pub const fn yz(self) -> Vec2<T> {
        vec2(self.y, self.z)
    }

    #[inline]
    pub const fn yw(self) -> Vec2<T> {
        vec2(self.y, self.w)
    }

    #[inline]
    pub const fn zx(self) -> Vec2<T> {
        vec2(self.z, self.x)
    }

    #[inline]
    pub const fn zy(self) -> Vec2<T> {
        vec2(self.z, self.y)
    }

    #[inline]
    pub const fn zw(self) -> Vec2<T> {
        vec2(self.z, self.w)
    }

    #[inline]
    pub const fn wx(self) -> Vec2<T> {
        vec2(self.w, self.x)
    }

    #[inline]
    pub const fn wy(self) -> Vec2<T> {
        vec2(self.w, self.y)
    }

    #[inline]
    pub const fn wz(self) -> Vec2<T> {
        vec2(self.w, self.z)
    }

    #[inline]
    pub const fn xyz(self) -> Vec3<T> {
        vec3(self.x, self.y, self.z)
    }

    #[inline]
    pub const fn xyw(self) -> Vec3<T> {
        vec3(self.x, self.y, self.w)
    }

    #[inline]
    pub const fn xzy(self) -> Vec3<T> {
        vec3(self.x, self.z, self.y)
    }

    #[inline]
    pub const fn xzw(self) -> Vec3<T> {
        vec3(self.x, self.z, self.w)
    }

    #[inline]
    pub const fn xwy(self) -> Vec3<T> {
        vec3(self.x, self.w, self.y)
    }

    #[inline]
    pub const fn xwz(self) -> Vec3<T> {
        vec3(self.x, self.w, self.z)
    }

    #[inline]
    pub const fn yxz(self) -> Vec3<T> {
        vec3(self.y, self.x, self.z)
    }

    #[inline]
    pub const fn yxw(self) -> Vec3<T> {
        vec3(self.y, self.x, self.w)
    }

    #[inline]
    pub const fn yzx(self) -> Vec3<T> {
        vec3(self.y, self.z, self.x)
    }

    #[inline]
    pub const fn yzw(self) -> Vec3<T> {
        vec3(self.y, self.z, self.w)
    }

    #[inline]
    pub const fn ywx(self) -> Vec3<T> {
        vec3(self.y, self.w, self.x)
    }

    #[inline]
    pub const fn ywz(self) -> Vec3<T> {
        vec3(self.y, self.w, self.z)
    }

    #[inline]
    pub const fn zxy(self) -> Vec3<T> {
        vec3(self.z, self.x, self.y)
    }

    #[inline]
    pub const fn zxw(self) -> Vec3<T> {
        vec3(self.z, self.x, self.w)
    }

    #[inline]
    pub const fn zyx(self) -> Vec3<T> {
        vec3(self.z, self.y, self.x)
    }

    #[inline]
    pub const fn zyw(self) -> Vec3<T> {
        vec3(self.z, self.y, self.w)
    }

    #[inline]
    pub const fn zwx(self) -> Vec3<T> {
        vec3(self.z, self.w, self.x)
    }

    #[inline]
    pub const fn zwy(self) -> Vec3<T> {
        vec3(self.z, self.w, self.y)
    }

    #[inline]
    pub const fn wxy(self) -> Vec3<T> {
        vec3(self.w, self.x, self.y)
    }

    #[inline]
    pub const fn wxz(self) -> Vec3<T> {
        vec3(self.w, self.x, self.z)
    }

    #[inline]
    pub const fn wyx(self) -> Vec3<T> {
        vec3(self.w, self.y, self.x)
    }

    #[inline]
    pub const fn wyz(self) -> Vec3<T> {
        vec3(self.w, self.y, self.z)
    }

    #[inline]
    pub const fn wzx(self) -> Vec3<T> {
        vec3(self.w, self.z, self.x)
    }

    #[inline]
    pub const fn wzy(self) -> Vec3<T> {
        vec3(self.w, self.z, self.y)
    }

    #[inline]
    pub const fn xyzw(self) -> Vec4<T> {
        vec4(self.x, self.y, self.z, self.w)
    }

    #[inline]
    pub const fn xywz(self) -> Vec4<T> {
        vec4(self.x, self.y, self.w, self.z)
    }

    #[inline]
    pub const fn xzyw(self) -> Vec4<T> {
        vec4(self.x, self.z, self.y, self.w)
    }

    #[inline]
    pub const fn xzwy(self) -> Vec4<T> {
        vec4(self.x, self.z, self.w, self.y)
    }

    #[inline]
    pub const fn xwyz(self) -> Vec4<T> {
        vec4(self.x, self.w, self.y, self.z)
    }

    #[inline]
    pub const fn xwzy(self) -> Vec4<T> {
        vec4(self.x, self.w, self.z, self.y)
    }

    #[inline]
    pub const fn yxzw(self) -> Vec4<T> {
        vec4(self.y, self.x, self.z, self.w)
    }

    #[inline]
    pub const fn yxwz(self) -> Vec4<T> {
        vec4(self.y, self.x, self.w, self.z)
    }

    #[inline]
    pub const fn yzxw(self) -> Vec4<T> {
        vec4(self.y, self.z, self.x, self.w)
    }

    #[inline]
    pub const fn yzwx(self) -> Vec4<T> {
        vec4(self.y, self.z, self.w, self.x)
    }

    #[inline]
    pub const fn ywxz(self) -> Vec4<T> {
        vec4(self.y, self.w, self.x, self.z)
    }

    #[inline]
    pub const fn ywzx(self) -> Vec4<T> {
        vec4(self.y, self.w, self.z, self.x)
    }

    #[inline]
    pub const fn zxyw(self) -> Vec4<T> {
        vec4(self.z, self.x, self.y, self.w)
    }

    #[inline]
    pub const fn zxwy(self) -> Vec4<T> {
        vec4(self.z, self.x, self.w, self.y)
    }

    #[inline]
    pub const fn zyxw(self) -> Vec4<T> {
        vec4(self.z, self.y, self.x, self.w)
    }

    #[inline]
    pub const fn zywx(self) -> Vec4<T> {
        vec4(self.z, self.y, self.w, self.x)
    }

    #[inline]
    pub const fn zwxy(self) -> Vec4<T> {
        vec4(self.z, self.w, self.x, self.y)
    }

    #[inline]
    pub const fn zwyx(self) -> Vec4<T> {
        vec4(self.z, self.w, self.y, self.x)
    }

    #[inline]
    pub const fn wxyz(self) -> Vec4<T> {
        vec4(self.w, self.x, self.y, self.z)
    }

    #[inline]
    pub const fn wxzy(self) -> Vec4<T> {
        vec4(self.w, self.x, self.z, self.y)
    }

    #[inline]
    pub const fn wyxz(self) -> Vec4<T> {
        vec4(self.w, self.y, self.x, self.z)
    }

    #[inline]
    pub const fn wyzx(self) -> Vec4<T> {
        vec4(self.w, self.y, self.z, self.x)
    }

    #[inline]
    pub const fn wzxy(self) -> Vec4<T> {
        vec4(self.w, self.z, self.x, self.y)
    }

    #[inline]
    pub const fn wzyx(self) -> Vec4<T> {
        vec4(self.w, self.z, self.y, self.x)
    }

    #[inline]
    pub const fn r(self) -> T {
        self.x
    }

    #[inline]
    pub const fn g(self) -> T {
        self.y
    }

    #[inline]
    pub const fn b(self) -> T {
        self.z
    }

    #[inline]
    pub const fn a(self) -> T {
        self.w
    }

    #[inline]
    pub const fn rg(self) -> Vec2<T> {
        vec2(self.x, self.y)
    }

    #[inline]
    pub const fn gr(self) -> Vec2<T> {
        vec2(self.y, self.x)
    }

    #[inline]
    pub const fn ba(self) -> Vec2<T> {
        vec2(self.z, self.w)
    }

    #[inline]
    pub const fn rgb(self) -> Vec3<T> {
        vec3(self.x, self.y, self.z)
    }

    #[inline]
    pub const fn rgba(self) -> Vec4<T> {
        vec4(self.x, self.y, self.z, self.w)
    }
}

impl<T: Scalar> Index<usize> for Vec4<T> {
    type Output = T;
    #[inline]
    fn index(&self, index: usize) -> &T {
        unimplemented_on_cpu()
    }
}
impl<T: Scalar> IndexMut<usize> for Vec4<T> {
    #[inline]
    fn index_mut(&mut self, index: usize) -> &mut T {
        unimplemented_on_cpu()
    }
}
impl<T: Scalar> From<(Vec2<T>, Vec2<T>)> for Vec4<T> {
    #[inline]
    fn from((a, b): (Vec2<T>, Vec2<T>)) -> Self {
        vec4(a.x, a.y, b.x, b.y)
    }
}

impl Vec4<f32> {
    /// Lane-wise `<`.
    #[inline]
    pub fn cmplt(self, rhs: Self) -> Vec4<bool> {
        unimplemented_on_cpu()
    }

    /// Lane-wise `<=`.
    #[inline]
    pub fn cmple(self, rhs: Self) -> Vec4<bool> {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>`.
    #[inline]
    pub fn cmpgt(self, rhs: Self) -> Vec4<bool> {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>=`.
    #[inline]
    pub fn cmpge(self, rhs: Self) -> Vec4<bool> {
        unimplemented_on_cpu()
    }
}
vector_ops!(Vec4<f32>, f32, Vec4<u32>, arith, neg);

impl Vec4<i32> {
    /// Lane-wise `<`.
    #[inline]
    pub fn cmplt(self, rhs: Self) -> Vec4<bool> {
        unimplemented_on_cpu()
    }

    /// Lane-wise `<=`.
    #[inline]
    pub fn cmple(self, rhs: Self) -> Vec4<bool> {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>`.
    #[inline]
    pub fn cmpgt(self, rhs: Self) -> Vec4<bool> {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>=`.
    #[inline]
    pub fn cmpge(self, rhs: Self) -> Vec4<bool> {
        unimplemented_on_cpu()
    }
}
vector_ops!(Vec4<i32>, i32, Vec4<u32>, arith, bitwise, shift, neg, not);

impl Vec4<u32> {
    /// Lane-wise `<`.
    #[inline]
    pub fn cmplt(self, rhs: Self) -> Vec4<bool> {
        unimplemented_on_cpu()
    }

    /// Lane-wise `<=`.
    #[inline]
    pub fn cmple(self, rhs: Self) -> Vec4<bool> {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>`.
    #[inline]
    pub fn cmpgt(self, rhs: Self) -> Vec4<bool> {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>=`.
    #[inline]
    pub fn cmpge(self, rhs: Self) -> Vec4<bool> {
        unimplemented_on_cpu()
    }
}
vector_ops!(Vec4<u32>, u32, Vec4<u32>, arith, bitwise, shift, not);

vector_ops!(Vec4<bool>, bool, Vec4<u32>, bitwise, not);

impl From<Vec2<f32>> for Vec2<i32> {
    #[inline]
    fn from(v: Vec2<f32>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec2<f32>> for Vec2<u32> {
    #[inline]
    fn from(v: Vec2<f32>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec2<f32>> for Vec2<bool> {
    #[inline]
    fn from(v: Vec2<f32>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec2<i32>> for Vec2<f32> {
    #[inline]
    fn from(v: Vec2<i32>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec2<i32>> for Vec2<u32> {
    #[inline]
    fn from(v: Vec2<i32>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec2<i32>> for Vec2<bool> {
    #[inline]
    fn from(v: Vec2<i32>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec2<u32>> for Vec2<f32> {
    #[inline]
    fn from(v: Vec2<u32>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec2<u32>> for Vec2<i32> {
    #[inline]
    fn from(v: Vec2<u32>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec2<u32>> for Vec2<bool> {
    #[inline]
    fn from(v: Vec2<u32>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec2<bool>> for Vec2<f32> {
    #[inline]
    fn from(v: Vec2<bool>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec2<bool>> for Vec2<i32> {
    #[inline]
    fn from(v: Vec2<bool>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec2<bool>> for Vec2<u32> {
    #[inline]
    fn from(v: Vec2<bool>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec3<f32>> for Vec3<i32> {
    #[inline]
    fn from(v: Vec3<f32>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec3<f32>> for Vec3<u32> {
    #[inline]
    fn from(v: Vec3<f32>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec3<f32>> for Vec3<bool> {
    #[inline]
    fn from(v: Vec3<f32>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec3<i32>> for Vec3<f32> {
    #[inline]
    fn from(v: Vec3<i32>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec3<i32>> for Vec3<u32> {
    #[inline]
    fn from(v: Vec3<i32>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec3<i32>> for Vec3<bool> {
    #[inline]
    fn from(v: Vec3<i32>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec3<u32>> for Vec3<f32> {
    #[inline]
    fn from(v: Vec3<u32>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec3<u32>> for Vec3<i32> {
    #[inline]
    fn from(v: Vec3<u32>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec3<u32>> for Vec3<bool> {
    #[inline]
    fn from(v: Vec3<u32>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec3<bool>> for Vec3<f32> {
    #[inline]
    fn from(v: Vec3<bool>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec3<bool>> for Vec3<i32> {
    #[inline]
    fn from(v: Vec3<bool>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec3<bool>> for Vec3<u32> {
    #[inline]
    fn from(v: Vec3<bool>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec4<f32>> for Vec4<i32> {
    #[inline]
    fn from(v: Vec4<f32>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec4<f32>> for Vec4<u32> {
    #[inline]
    fn from(v: Vec4<f32>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec4<f32>> for Vec4<bool> {
    #[inline]
    fn from(v: Vec4<f32>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec4<i32>> for Vec4<f32> {
    #[inline]
    fn from(v: Vec4<i32>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec4<i32>> for Vec4<u32> {
    #[inline]
    fn from(v: Vec4<i32>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec4<i32>> for Vec4<bool> {
    #[inline]
    fn from(v: Vec4<i32>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec4<u32>> for Vec4<f32> {
    #[inline]
    fn from(v: Vec4<u32>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec4<u32>> for Vec4<i32> {
    #[inline]
    fn from(v: Vec4<u32>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec4<u32>> for Vec4<bool> {
    #[inline]
    fn from(v: Vec4<u32>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec4<bool>> for Vec4<f32> {
    #[inline]
    fn from(v: Vec4<bool>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec4<bool>> for Vec4<i32> {
    #[inline]
    fn from(v: Vec4<bool>) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<Vec4<bool>> for Vec4<u32> {
    #[inline]
    fn from(v: Vec4<bool>) -> Self {
        unimplemented_on_cpu()
    }
}
