//! Vector types.
//!
//! Generated by `generate_vector.py`, then `cargo fmt`; edit that, not this.
//!
//! `Vec3<T>` is WGSL's `vec3<T>`, and a bare `Vec3` is `Vec3<f32>`, as `vec3f`
//! is. `vec3(x, y, z)` builds one of whatever its components are:
//! `vec3(0.0, 1.0, 0.0)` is a `Vec3<f32>` and `vec3(1, 2, 3)` a `Vec3<i32>`, as
//! WGSL's literals go, and `vec3::<u32>(1, 2, 3)` says which outright:
//!
//! ```
//! use synaga_shader::*;
//!
//! let up = vec3(0.0, 1.0, 0.0);
//! let cell = vec2(3, 4);
//! let size = vec2::<u32>(640, 480);
//! # use core::any::{type_name, type_name_of_val as of};
//! # assert_eq!(of(&up), type_name::<Vec3<f32>>());
//! # assert_eq!(of(&cell), type_name::<Vec2<i32>>());
//! # assert_eq!(of(&size), type_name::<Vec2<u32>>());
//! ```
//!
//! Component access splits two ways: a single `x`/`y`/`z`/`w` is a field, so
//! `v.x` reads and `v.x = 1.0` writes, while every other swizzle is a method.
//! Rust has no way to give one piece of memory a hundred overlapping names, so
//! `v.xyz` has to be `v.xyz()`; `.r`/`.g`/`.b`/`.a` are methods for the same
//! reason, since they would alias the `x`/`y`/`z`/`w` fields.
//!
//! Comparisons come two ways. The lane-wise ones are methods, `a.cmplt(b)`
//! and the rest, as glam spells them, because Rust's `<` has to give one
//! `bool`. That `bool` holds when it holds in every lane: `a < b` is
//! `a.cmplt(b).all()`, `a == b` is `a.cmpeq(b).all()`, and `a != b` is its
//! negation, some lane differing. So `!(a < b)` is not `a >= b`: it is "some
//! lane is not less", `a.cmpge(b).any()`, which is what a bounds check wants.
//!
//! So is the math, named as `f32` names it, and as glam does for what only a
//! vector has. `cast` converts the lanes, as `as` converts a scalar:
//!
//! ```
//! use synaga_shader::*;
//!
//! fn lambert(normal: Vec3, light: Vec3) -> f32 {
//!     normal.normalize().dot(light).max(0.0)
//! }
//! fn inside(p: Vec2<i32>, extent: Vec2<i32>) -> bool {
//!     p.cmpge(Vec2::ZERO).all() && p.cmplt(extent).all()
//! }
//! fn texel(uv: Vec2, size: Vec2<u32>) -> Vec2<i32> {
//!     (uv * size.cast::<f32>()).cast()
//! }
//! # assert_eq!(lambert(vec3(0.0, 0.0, 2.0), vec3(0.0, 0.6, 0.8)), 0.8);
//! # assert!(inside(vec2(1, 2), vec2(4, 4)) && !inside(vec2(-1, 2), vec2(4, 4)));
//! # assert_eq!(texel(vec2(0.5, 0.25), vec2(640, 480)), vec2(320, 120));
//! ```
//!
//! Each means what the Rust method of that name means, which for two of them
//! is not what the GPU builtin of that name does: `v.fract()` is
//! `v - v.trunc()`, and the GPU's rounding is `v.round_ties_even()`. The free
//! functions, `fract(v)` and `round(v)`, are the GPU's.
//!
//! All of it runs on the CPU too, lane by lane, as Rust runs the scalar
//! code: `+` on a `Vec3<u32>` panics on overflow where `+` on a `u32` would,
//! and `wrapping_add` wraps, as the GPU's `+` does.

use core::ops::*;

/// What a vector's lanes hold: `f32`, `i32`, `u32` or `bool`.
///
/// The bound is also what makes `vec3(0.0, 1.0, 0.0)` a `Vec3<f32>`: `f32` is
/// the one float type that is a `Scalar`, so Rust gives the literals that type
/// rather than its usual `f64`.
pub trait Scalar: Copy + PartialEq + PartialOrd + sealed::Sealed {
    /// Zero, or `false`.
    const ZERO: Self;
    /// One, or `true`.
    const ONE: Self;
}

mod sealed {
    /// How a lane converts to another, as `as` converts a primitive. Out of
    /// reach outside this crate, so it adds no methods to `f32` and the rest.
    pub trait Sealed: Copy {
        fn to_f32(self) -> f32;
        fn to_i32(self) -> i32;
        fn to_u32(self) -> u32;
        /// `true` unless it is zero, as the GPU's `bool(x)`.
        fn to_bool(self) -> bool;
        /// `lane as Self`.
        fn convert<S: Sealed>(lane: S) -> Self;
    }

    impl Sealed for f32 {
        #[inline]
        fn to_f32(self) -> f32 {
            self
        }
        #[inline]
        fn to_i32(self) -> i32 {
            self as i32
        }
        #[inline]
        fn to_u32(self) -> u32 {
            self as u32
        }
        #[inline]
        fn to_bool(self) -> bool {
            self != 0.0
        }
        #[inline]
        fn convert<S: Sealed>(lane: S) -> Self {
            lane.to_f32()
        }
    }
    impl Sealed for i32 {
        #[inline]
        fn to_f32(self) -> f32 {
            self as f32
        }
        #[inline]
        fn to_i32(self) -> i32 {
            self
        }
        #[inline]
        fn to_u32(self) -> u32 {
            self as u32
        }
        #[inline]
        fn to_bool(self) -> bool {
            self != 0
        }
        #[inline]
        fn convert<S: Sealed>(lane: S) -> Self {
            lane.to_i32()
        }
    }
    impl Sealed for u32 {
        #[inline]
        fn to_f32(self) -> f32 {
            self as f32
        }
        #[inline]
        fn to_i32(self) -> i32 {
            self as i32
        }
        #[inline]
        fn to_u32(self) -> u32 {
            self
        }
        #[inline]
        fn to_bool(self) -> bool {
            self != 0
        }
        #[inline]
        fn convert<S: Sealed>(lane: S) -> Self {
            lane.to_u32()
        }
    }
    impl Sealed for bool {
        #[inline]
        fn to_f32(self) -> f32 {
            self as u32 as f32
        }
        #[inline]
        fn to_i32(self) -> i32 {
            self as i32
        }
        #[inline]
        fn to_u32(self) -> u32 {
            self as u32
        }
        #[inline]
        fn to_bool(self) -> bool {
            self
        }
        #[inline]
        fn convert<S: Sealed>(lane: S) -> Self {
            lane.to_bool()
        }
    }
}

impl Scalar for f32 {
    const ZERO: Self = 0.0;
    const ONE: Self = 1.0;
}
impl Scalar for i32 {
    const ZERO: Self = 0;
    const ONE: Self = 1;
}
impl Scalar for u32 {
    const ZERO: Self = 0;
    const ONE: Self = 1;
}
impl Scalar for bool {
    const ZERO: Self = false;
    const ONE: Self = true;
}

/// The operators every vector has, and the ones only some do.
///
/// `macro_rules!` cannot paste `Add` and `Assign` into one identifier, so each
/// operator names its assigning form too. `$shift` is the `VecN<u32>` a
/// lane-wise shift takes, since WGSL wants an unsigned shift amount whatever
/// is shifted.
macro_rules! vector_ops {
    ($name:ty, $scalar:ty, $shift:ty $(, $group:ident)*) => {
        $(vector_ops!(@group $group, $name, $scalar, $shift);)*
    };

    (@group arith, $name:ty, $scalar:ty, $shift:ty) => {
        vector_ops!(@scalar_too Add, add, AddAssign, add_assign, $name, $scalar);
        vector_ops!(@scalar_too Sub, sub, SubAssign, sub_assign, $name, $scalar);
        vector_ops!(@scalar_too Mul, mul, MulAssign, mul_assign, $name, $scalar);
        vector_ops!(@scalar_too Div, div, DivAssign, div_assign, $name, $scalar);
        vector_ops!(@scalar_too Rem, rem, RemAssign, rem_assign, $name, $scalar);
    };
    (@group bitwise, $name:ty, $scalar:ty, $shift:ty) => {
        vector_ops!(@scalar_too BitAnd, bitand, BitAndAssign, bitand_assign, $name, $scalar);
        vector_ops!(@scalar_too BitOr, bitor, BitOrAssign, bitor_assign, $name, $scalar);
        vector_ops!(@scalar_too BitXor, bitxor, BitXorAssign, bitxor_assign, $name, $scalar);
    };
    (@group shift, $name:ty, $scalar:ty, $shift:ty) => {
        vector_ops!(@shift Shl, shl, ShlAssign, shl_assign, $name, $shift);
        vector_ops!(@shift Shr, shr, ShrAssign, shr_assign, $name, $shift);
    };
    (@group neg, $name:ty, $scalar:ty, $shift:ty) => {
        impl Neg for $name {
            type Output = Self;
            #[inline]
            fn neg(self) -> Self { self.map_lanes(|a| -a) }
        }
    };
    (@group not, $name:ty, $scalar:ty, $shift:ty) => {
        impl Not for $name {
            type Output = Self;
            #[inline]
            fn not(self) -> Self { self.map_lanes(|a| !a) }
        }
    };

    // Arithmetic and bitwise operators also work against a scalar, from
    // either side, as glam's do: a shader writes both `v * 2.0` and
    // `2.0 * v`, and `bits & 0xFF`.
    (@scalar_too $trait:ident, $method:ident, $assign:ident, $assign_fn:ident,
     $name:ty, $scalar:ty) => {
        vector_ops!(@lanewise $trait, $method, $assign, $assign_fn, $name);
        impl $trait<$scalar> for $name {
            type Output = Self;
            #[inline]
            fn $method(self, rhs: $scalar) -> Self { self.map_lanes(|a| $trait::$method(a, rhs)) }
        }
        impl $trait<$name> for $scalar {
            type Output = $name;
            #[inline]
            fn $method(self, rhs: $name) -> $name { rhs.map_lanes(|b| $trait::$method(self, b)) }
        }
        impl $assign<$scalar> for $name {
            #[inline]
            fn $assign_fn(&mut self, rhs: $scalar) { *self = $trait::$method(*self, rhs) }
        }
    };
    (@lanewise $trait:ident, $method:ident, $assign:ident, $assign_fn:ident, $name:ty) => {
        impl $trait for $name {
            type Output = Self;
            #[inline]
            fn $method(self, rhs: Self) -> Self { self.zip_lanes(rhs, $trait::$method) }
        }
        impl $assign for $name {
            #[inline]
            fn $assign_fn(&mut self, rhs: Self) { *self = $trait::$method(*self, rhs) }
        }
    };
    (@shift $trait:ident, $method:ident, $assign:ident, $assign_fn:ident,
     $name:ty, $shift:ty) => {
        impl $trait<$shift> for $name {
            type Output = Self;
            #[inline]
            fn $method(self, rhs: $shift) -> Self { self.zip_lanes(rhs, $trait::$method) }
        }
        impl $trait<u32> for $name {
            type Output = Self;
            #[inline]
            fn $method(self, rhs: u32) -> Self { self.map_lanes(|a| $trait::$method(a, rhs)) }
        }
        impl $assign<$shift> for $name {
            #[inline]
            fn $assign_fn(&mut self, rhs: $shift) { *self = $trait::$method(*self, rhs) }
        }
        impl $assign<u32> for $name {
            #[inline]
            fn $assign_fn(&mut self, rhs: u32) { *self = $trait::$method(*self, rhs) }
        }
    };
}

/// The math on a vector, named as Rust names it: `f32`'s own methods
/// (`v.sqrt()`, `v.max(w)`, `v.mul_add(a, b)`), and glam's for what only a
/// vector has (`v.dot(w)`, `v.normalize()`, `a.lerp(b, t)`).
///
/// Each means what the Rust method means, on the CPU as on the GPU. Two of
/// the GPU's builtins round differently from the Rust methods of the same
/// name, so `fract` here is `self - self.trunc()` as `f32::fract` is, and the
/// GPU's `round`, which takes a half to the even neighbour, is
/// `round_ties_even`. The free functions keep WGSL's names and meanings:
/// `fract(v)` is `v - floor(v)`.
macro_rules! vector_math {
    ($name:ty, $scalar:ty $(, $group:ident)*) => {
        $(vector_math!(@group $group, $name, $scalar);)*
    };

    (@group ord, $name:ty, $scalar:ty) => {
        impl $name {
            /// The lesser of each pair of lanes.
            #[inline]
            pub fn min(self, rhs: Self) -> Self { self.zip_lanes(rhs, |a, b| a.min(b)) }
            /// The greater of each pair of lanes.
            #[inline]
            pub fn max(self, rhs: Self) -> Self { self.zip_lanes(rhs, |a, b| a.max(b)) }
            /// Each lane held between the lanes of `min` and `max`, which
            /// have to be in order.
            #[inline]
            pub fn clamp(self, min: Self, max: Self) -> Self {
                debug_assert!(min.cmple(max).all(), "clamp: expected min <= max");
                self.max(min).min(max)
            }
            /// The sum of the lane-wise products.
            #[inline]
            pub fn dot(self, rhs: Self) -> $scalar { (self * rhs).element_sum() }
            /// The sum of the lanes.
            #[inline]
            pub fn element_sum(self) -> $scalar { self.reduce_lanes(|a, b| a + b) }
        }
    };
    (@group signed, $name:ty, $scalar:ty) => {
        impl $name {
            /// The magnitude of each lane.
            #[inline]
            pub fn abs(self) -> Self { self.map_lanes(<$scalar>::abs) }
            /// `-1`, `0` or `1` per lane, by its sign.
            #[inline]
            pub fn signum(self) -> Self { self.map_lanes(<$scalar>::signum) }
        }
    };
    (@group float, $name:ty, $scalar:ty) => {
        vector_math!(@lanewise $name, $scalar, abs floor ceil trunc round_ties_even fract sqrt
            recip exp exp2 ln log2 sin cos tan asin acos atan sinh cosh tanh asinh acosh atanh
            to_degrees to_radians);
        impl $name {
            /// This direction at unit length: `self / self.length()`.
            #[inline]
            pub fn normalize(self) -> Self { self * self.length().recip() }
            /// Each lane raised to the power `n`.
            #[inline]
            pub fn powf(self, n: $scalar) -> Self { self.map_lanes(|a| a.powf(n)) }
            /// The angle of each pair of lanes, `self` being `y`, as `f32::atan2`.
            #[inline]
            pub fn atan2(self, x: Self) -> Self { self.zip_lanes(x, <$scalar>::atan2) }
            /// `self * a + b`: the GPU's `fma`.
            #[inline]
            pub fn mul_add(self, a: Self, b: Self) -> Self {
                self.zip3_lanes(a, b, <$scalar>::mul_add)
            }
            /// The Euclidean length.
            #[inline]
            pub fn length(self) -> $scalar { self.dot(self).sqrt() }
            /// The squared length, which saves the square root.
            #[inline]
            pub fn length_squared(self) -> $scalar { self.dot(self) }
            /// The distance to `rhs`.
            #[inline]
            pub fn distance(self, rhs: Self) -> $scalar { (self - rhs).length() }
            /// This direction reflected off a surface facing `normal`, which
            /// has to be normalized.
            #[inline]
            pub fn reflect(self, normal: Self) -> Self { self - 2.0 * self.dot(normal) * normal }
            /// This direction refracted through a surface facing `normal`,
            /// with `eta` the ratio of the indices of refraction. Zero where
            /// the light is reflected entirely.
            #[inline]
            pub fn refract(self, normal: Self, eta: $scalar) -> Self {
                let n_dot_i = normal.dot(self);
                let k = 1.0 - eta * eta * (1.0 - n_dot_i * n_dot_i);
                if k >= 0.0 {
                    eta * self - (eta * n_dot_i + k.sqrt()) * normal
                } else {
                    Self::ZERO
                }
            }
            /// `self` at `s == 0` and `rhs` at `s == 1`: the GPU's `mix`.
            #[inline]
            pub fn lerp(self, rhs: Self, s: $scalar) -> Self { self * (1.0 - s) + rhs * s }
        }
    };
    (@group wrapping, $name:ty, $scalar:ty) => {
        impl $name {
            /// Lane-wise `+`, wrapping around on overflow, as the GPU's `+`
            /// does, rather than panicking as Rust's does under overflow checks.
            #[inline]
            pub fn wrapping_add(self, rhs: Self) -> Self {
                self.zip_lanes(rhs, <$scalar>::wrapping_add)
            }
            /// Lane-wise `-`, wrapping around on overflow.
            #[inline]
            pub fn wrapping_sub(self, rhs: Self) -> Self {
                self.zip_lanes(rhs, <$scalar>::wrapping_sub)
            }
            /// Lane-wise `*`, wrapping around on overflow.
            #[inline]
            pub fn wrapping_mul(self, rhs: Self) -> Self {
                self.zip_lanes(rhs, <$scalar>::wrapping_mul)
            }
            /// Each lane negated, wrapping around on overflow: `0 - self`.
            #[inline]
            pub fn wrapping_neg(self) -> Self { self.map_lanes(<$scalar>::wrapping_neg) }
        }
    };
    (@group bool, $name:ty, $scalar:ty) => {
        impl $name {
            /// Whether every lane is `true`.
            #[inline]
            pub fn all(self) -> bool { self.reduce_lanes(|a, b| a & b) }
            /// Whether any lane is `true`.
            #[inline]
            pub fn any(self) -> bool { self.reduce_lanes(|a, b| a | b) }
        }
    };

    // One-lane-in, one-lane-out methods that `f32` has under the same name,
    // with the same meaning, which is all their documentation needs to say.
    (@lanewise $name:ty, $scalar:ty, $($method:ident)*) => {
        impl $name {
            $(
                #[doc = concat!("`f32::", stringify!($method), "` on each lane.")]
                #[inline]
                pub fn $method(self) -> Self { self.map_lanes(<$scalar>::$method) }
            )*
        }
    };
}

/// `vec2<T>` in WGSL. A bare `Vec2` is `Vec2<f32>`, WGSL's `vec2f`.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
#[repr(C)]
pub struct Vec2<T = f32> {
    pub x: T,
    pub y: T,
}

/// Build a [`Vec2`] from its components.
#[inline]
pub const fn vec2<T: Scalar>(x: T, y: T) -> Vec2<T> {
    Vec2 { x, y }
}

impl<T: Scalar> Vec2<T> {
    pub const ZERO: Self = vec2(T::ZERO, T::ZERO);
    pub const ONE: Self = vec2(T::ONE, T::ONE);

    /// Every lane set to `v`.
    #[inline]
    pub const fn splat(v: T) -> Self {
        vec2(v, v)
    }

    /// Each lane converted to `U`, as `as` converts a scalar: `v.cast::<i32>()`
    /// is WGSL's `vec2<i32>(v)`. Into `bool`, a lane is `true` unless it is zero.
    #[inline]
    pub fn cast<U: Scalar>(self) -> Vec2<U> {
        self.map_lanes(U::convert)
    }

    /// `f` of each lane.
    #[inline]
    pub(crate) fn map_lanes<U: Scalar>(self, f: impl Fn(T) -> U) -> Vec2<U> {
        vec2(f(self.x), f(self.y))
    }

    /// `f` of each pair of lanes.
    #[inline]
    pub(crate) fn zip_lanes<U: Scalar, V: Scalar>(
        self,
        rhs: Vec2<U>,
        f: impl Fn(T, U) -> V,
    ) -> Vec2<V> {
        vec2(f(self.x, rhs.x), f(self.y, rhs.y))
    }

    /// `f` of each three lanes.
    #[inline]
    pub(crate) fn zip3_lanes(self, b: Self, c: Self, f: impl Fn(T, T, T) -> T) -> Self {
        vec2(f(self.x, b.x, c.x), f(self.y, b.y, c.y))
    }

    /// The lanes, combined first to last.
    #[inline]
    pub(crate) fn reduce_lanes(self, f: impl Fn(T, T) -> T) -> T {
        f(self.x, self.y)
    }

    /// One lane wider, with `z` appended. This is how a shader's
    /// `vec3(v, z)` is spelled.
    #[inline]
    pub const fn extend(self, z: T) -> Vec3<T> {
        vec3(self.x, self.y, z)
    }

    /// Lane-wise `==`.
    #[inline]
    pub fn cmpeq(self, rhs: Self) -> Vec2<bool> {
        self.zip_lanes(rhs, |a, b| a == b)
    }

    /// Lane-wise `!=`.
    #[inline]
    pub fn cmpne(self, rhs: Self) -> Vec2<bool> {
        self.zip_lanes(rhs, |a, b| a != b)
    }

    #[inline]
    pub const fn xy(self) -> Vec2<T> {
        vec2(self.x, self.y)
    }

    #[inline]
    pub const fn yx(self) -> Vec2<T> {
        vec2(self.y, self.x)
    }

    #[inline]
    pub const fn r(self) -> T {
        self.x
    }

    #[inline]
    pub const fn g(self) -> T {
        self.y
    }

    #[inline]
    pub const fn rg(self) -> Vec2<T> {
        vec2(self.x, self.y)
    }

    #[inline]
    pub const fn gr(self) -> Vec2<T> {
        vec2(self.y, self.x)
    }
}

impl<T: Scalar> Index<usize> for Vec2<T> {
    type Output = T;
    #[inline]
    fn index(&self, index: usize) -> &T {
        match index {
            0 => &self.x,
            1 => &self.y,
            _ => panic!("lane {index} of a Vec2"),
        }
    }
}
impl<T: Scalar> IndexMut<usize> for Vec2<T> {
    #[inline]
    fn index_mut(&mut self, index: usize) -> &mut T {
        match index {
            0 => &mut self.x,
            1 => &mut self.y,
            _ => panic!("lane {index} of a Vec2"),
        }
    }
}

impl Vec2<f32> {
    /// Lane-wise `<`.
    #[inline]
    pub fn cmplt(self, rhs: Self) -> Vec2<bool> {
        self.zip_lanes(rhs, |a, b| a < b)
    }

    /// Lane-wise `<=`.
    #[inline]
    pub fn cmple(self, rhs: Self) -> Vec2<bool> {
        self.zip_lanes(rhs, |a, b| a <= b)
    }

    /// Lane-wise `>`.
    #[inline]
    pub fn cmpgt(self, rhs: Self) -> Vec2<bool> {
        self.zip_lanes(rhs, |a, b| a > b)
    }

    /// Lane-wise `>=`.
    #[inline]
    pub fn cmpge(self, rhs: Self) -> Vec2<bool> {
        self.zip_lanes(rhs, |a, b| a >= b)
    }
}
/// `a < b` when every lane is, as `a.cmplt(b).all()`, and so for `<=`, `>`
/// and `>=`. `partial_cmp` is `Equal`, `Less` or `Greater` when every lane
/// agrees, and `None` otherwise. So `a <= b` holds more often than
/// `a < b || a == b`, which `PartialOrd` asks of it, as it does in nalgebra.
impl PartialOrd for Vec2<f32> {
    #[inline]
    fn partial_cmp(&self, other: &Self) -> Option<core::cmp::Ordering> {
        use core::cmp::Ordering::*;
        match (self == other, self < other, self > other) {
            (true, _, _) => Some(Equal),
            (_, true, _) => Some(Less),
            (_, _, true) => Some(Greater),
            _ => None,
        }
    }
    #[inline]
    fn lt(&self, other: &Self) -> bool {
        self.cmplt(*other).all()
    }
    #[inline]
    fn le(&self, other: &Self) -> bool {
        self.cmple(*other).all()
    }
    #[inline]
    fn gt(&self, other: &Self) -> bool {
        self.cmpgt(*other).all()
    }
    #[inline]
    fn ge(&self, other: &Self) -> bool {
        self.cmpge(*other).all()
    }
}
vector_ops!(Vec2<f32>, f32, Vec2<u32>, arith, neg);
vector_math!(Vec2<f32>, f32, ord, float);

impl Vec2<i32> {
    /// Lane-wise `<`.
    #[inline]
    pub fn cmplt(self, rhs: Self) -> Vec2<bool> {
        self.zip_lanes(rhs, |a, b| a < b)
    }

    /// Lane-wise `<=`.
    #[inline]
    pub fn cmple(self, rhs: Self) -> Vec2<bool> {
        self.zip_lanes(rhs, |a, b| a <= b)
    }

    /// Lane-wise `>`.
    #[inline]
    pub fn cmpgt(self, rhs: Self) -> Vec2<bool> {
        self.zip_lanes(rhs, |a, b| a > b)
    }

    /// Lane-wise `>=`.
    #[inline]
    pub fn cmpge(self, rhs: Self) -> Vec2<bool> {
        self.zip_lanes(rhs, |a, b| a >= b)
    }
}
/// `a < b` when every lane is, as `a.cmplt(b).all()`, and so for `<=`, `>`
/// and `>=`. `partial_cmp` is `Equal`, `Less` or `Greater` when every lane
/// agrees, and `None` otherwise. So `a <= b` holds more often than
/// `a < b || a == b`, which `PartialOrd` asks of it, as it does in nalgebra.
impl PartialOrd for Vec2<i32> {
    #[inline]
    fn partial_cmp(&self, other: &Self) -> Option<core::cmp::Ordering> {
        use core::cmp::Ordering::*;
        match (self == other, self < other, self > other) {
            (true, _, _) => Some(Equal),
            (_, true, _) => Some(Less),
            (_, _, true) => Some(Greater),
            _ => None,
        }
    }
    #[inline]
    fn lt(&self, other: &Self) -> bool {
        self.cmplt(*other).all()
    }
    #[inline]
    fn le(&self, other: &Self) -> bool {
        self.cmple(*other).all()
    }
    #[inline]
    fn gt(&self, other: &Self) -> bool {
        self.cmpgt(*other).all()
    }
    #[inline]
    fn ge(&self, other: &Self) -> bool {
        self.cmpge(*other).all()
    }
}
vector_ops!(Vec2<i32>, i32, Vec2<u32>, arith, bitwise, shift, neg, not);
vector_math!(Vec2<i32>, i32, ord, signed, wrapping);

impl Vec2<u32> {
    /// Lane-wise `<`.
    #[inline]
    pub fn cmplt(self, rhs: Self) -> Vec2<bool> {
        self.zip_lanes(rhs, |a, b| a < b)
    }

    /// Lane-wise `<=`.
    #[inline]
    pub fn cmple(self, rhs: Self) -> Vec2<bool> {
        self.zip_lanes(rhs, |a, b| a <= b)
    }

    /// Lane-wise `>`.
    #[inline]
    pub fn cmpgt(self, rhs: Self) -> Vec2<bool> {
        self.zip_lanes(rhs, |a, b| a > b)
    }

    /// Lane-wise `>=`.
    #[inline]
    pub fn cmpge(self, rhs: Self) -> Vec2<bool> {
        self.zip_lanes(rhs, |a, b| a >= b)
    }
}
/// `a < b` when every lane is, as `a.cmplt(b).all()`, and so for `<=`, `>`
/// and `>=`. `partial_cmp` is `Equal`, `Less` or `Greater` when every lane
/// agrees, and `None` otherwise. So `a <= b` holds more often than
/// `a < b || a == b`, which `PartialOrd` asks of it, as it does in nalgebra.
impl PartialOrd for Vec2<u32> {
    #[inline]
    fn partial_cmp(&self, other: &Self) -> Option<core::cmp::Ordering> {
        use core::cmp::Ordering::*;
        match (self == other, self < other, self > other) {
            (true, _, _) => Some(Equal),
            (_, true, _) => Some(Less),
            (_, _, true) => Some(Greater),
            _ => None,
        }
    }
    #[inline]
    fn lt(&self, other: &Self) -> bool {
        self.cmplt(*other).all()
    }
    #[inline]
    fn le(&self, other: &Self) -> bool {
        self.cmple(*other).all()
    }
    #[inline]
    fn gt(&self, other: &Self) -> bool {
        self.cmpgt(*other).all()
    }
    #[inline]
    fn ge(&self, other: &Self) -> bool {
        self.cmpge(*other).all()
    }
}
vector_ops!(Vec2<u32>, u32, Vec2<u32>, arith, bitwise, shift, not);
vector_math!(Vec2<u32>, u32, ord, wrapping);

vector_ops!(Vec2<bool>, bool, Vec2<u32>, bitwise, not);
vector_math!(Vec2<bool>, bool, bool);

/// `vec3<T>` in WGSL. A bare `Vec3` is `Vec3<f32>`, WGSL's `vec3f`.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
#[repr(C)]
pub struct Vec3<T = f32> {
    pub x: T,
    pub y: T,
    pub z: T,
}

/// Build a [`Vec3`] from its components.
#[inline]
pub const fn vec3<T: Scalar>(x: T, y: T, z: T) -> Vec3<T> {
    Vec3 { x, y, z }
}

impl<T: Scalar> Vec3<T> {
    pub const ZERO: Self = vec3(T::ZERO, T::ZERO, T::ZERO);
    pub const ONE: Self = vec3(T::ONE, T::ONE, T::ONE);

    /// Every lane set to `v`.
    #[inline]
    pub const fn splat(v: T) -> Self {
        vec3(v, v, v)
    }

    /// Each lane converted to `U`, as `as` converts a scalar: `v.cast::<i32>()`
    /// is WGSL's `vec3<i32>(v)`. Into `bool`, a lane is `true` unless it is zero.
    #[inline]
    pub fn cast<U: Scalar>(self) -> Vec3<U> {
        self.map_lanes(U::convert)
    }

    /// `f` of each lane.
    #[inline]
    pub(crate) fn map_lanes<U: Scalar>(self, f: impl Fn(T) -> U) -> Vec3<U> {
        vec3(f(self.x), f(self.y), f(self.z))
    }

    /// `f` of each pair of lanes.
    #[inline]
    pub(crate) fn zip_lanes<U: Scalar, V: Scalar>(
        self,
        rhs: Vec3<U>,
        f: impl Fn(T, U) -> V,
    ) -> Vec3<V> {
        vec3(f(self.x, rhs.x), f(self.y, rhs.y), f(self.z, rhs.z))
    }

    /// `f` of each three lanes.
    #[inline]
    pub(crate) fn zip3_lanes(self, b: Self, c: Self, f: impl Fn(T, T, T) -> T) -> Self {
        vec3(
            f(self.x, b.x, c.x),
            f(self.y, b.y, c.y),
            f(self.z, b.z, c.z),
        )
    }

    /// The lanes, combined first to last.
    #[inline]
    pub(crate) fn reduce_lanes(self, f: impl Fn(T, T) -> T) -> T {
        f(f(self.x, self.y), self.z)
    }

    /// One lane wider, with `w` appended. This is how a shader's
    /// `vec4(v, w)` is spelled.
    #[inline]
    pub const fn extend(self, w: T) -> Vec4<T> {
        vec4(self.x, self.y, self.z, w)
    }

    /// One lane narrower, dropping the last.
    #[inline]
    pub const fn truncate(self) -> Vec2<T> {
        vec2(self.x, self.y)
    }

    /// Lane-wise `==`.
    #[inline]
    pub fn cmpeq(self, rhs: Self) -> Vec3<bool> {
        self.zip_lanes(rhs, |a, b| a == b)
    }

    /// Lane-wise `!=`.
    #[inline]
    pub fn cmpne(self, rhs: Self) -> Vec3<bool> {
        self.zip_lanes(rhs, |a, b| a != b)
    }

    #[inline]
    pub const fn xy(self) -> Vec2<T> {
        vec2(self.x, self.y)
    }

    #[inline]
    pub const fn xz(self) -> Vec2<T> {
        vec2(self.x, self.z)
    }

    #[inline]
    pub const fn yx(self) -> Vec2<T> {
        vec2(self.y, self.x)
    }

    #[inline]
    pub const fn yz(self) -> Vec2<T> {
        vec2(self.y, self.z)
    }

    #[inline]
    pub const fn zx(self) -> Vec2<T> {
        vec2(self.z, self.x)
    }

    #[inline]
    pub const fn zy(self) -> Vec2<T> {
        vec2(self.z, self.y)
    }

    #[inline]
    pub const fn xyz(self) -> Vec3<T> {
        vec3(self.x, self.y, self.z)
    }

    #[inline]
    pub const fn xzy(self) -> Vec3<T> {
        vec3(self.x, self.z, self.y)
    }

    #[inline]
    pub const fn yxz(self) -> Vec3<T> {
        vec3(self.y, self.x, self.z)
    }

    #[inline]
    pub const fn yzx(self) -> Vec3<T> {
        vec3(self.y, self.z, self.x)
    }

    #[inline]
    pub const fn zxy(self) -> Vec3<T> {
        vec3(self.z, self.x, self.y)
    }

    #[inline]
    pub const fn zyx(self) -> Vec3<T> {
        vec3(self.z, self.y, self.x)
    }

    #[inline]
    pub const fn r(self) -> T {
        self.x
    }

    #[inline]
    pub const fn g(self) -> T {
        self.y
    }

    #[inline]
    pub const fn b(self) -> T {
        self.z
    }

    #[inline]
    pub const fn rg(self) -> Vec2<T> {
        vec2(self.x, self.y)
    }

    #[inline]
    pub const fn gr(self) -> Vec2<T> {
        vec2(self.y, self.x)
    }

    #[inline]
    pub const fn rgb(self) -> Vec3<T> {
        vec3(self.x, self.y, self.z)
    }
}

impl<T: Scalar> Index<usize> for Vec3<T> {
    type Output = T;
    #[inline]
    fn index(&self, index: usize) -> &T {
        match index {
            0 => &self.x,
            1 => &self.y,
            2 => &self.z,
            _ => panic!("lane {index} of a Vec3"),
        }
    }
}
impl<T: Scalar> IndexMut<usize> for Vec3<T> {
    #[inline]
    fn index_mut(&mut self, index: usize) -> &mut T {
        match index {
            0 => &mut self.x,
            1 => &mut self.y,
            2 => &mut self.z,
            _ => panic!("lane {index} of a Vec3"),
        }
    }
}

impl Vec3<f32> {
    /// Lane-wise `<`.
    #[inline]
    pub fn cmplt(self, rhs: Self) -> Vec3<bool> {
        self.zip_lanes(rhs, |a, b| a < b)
    }

    /// Lane-wise `<=`.
    #[inline]
    pub fn cmple(self, rhs: Self) -> Vec3<bool> {
        self.zip_lanes(rhs, |a, b| a <= b)
    }

    /// Lane-wise `>`.
    #[inline]
    pub fn cmpgt(self, rhs: Self) -> Vec3<bool> {
        self.zip_lanes(rhs, |a, b| a > b)
    }

    /// Lane-wise `>=`.
    #[inline]
    pub fn cmpge(self, rhs: Self) -> Vec3<bool> {
        self.zip_lanes(rhs, |a, b| a >= b)
    }
}
/// `a < b` when every lane is, as `a.cmplt(b).all()`, and so for `<=`, `>`
/// and `>=`. `partial_cmp` is `Equal`, `Less` or `Greater` when every lane
/// agrees, and `None` otherwise. So `a <= b` holds more often than
/// `a < b || a == b`, which `PartialOrd` asks of it, as it does in nalgebra.
impl PartialOrd for Vec3<f32> {
    #[inline]
    fn partial_cmp(&self, other: &Self) -> Option<core::cmp::Ordering> {
        use core::cmp::Ordering::*;
        match (self == other, self < other, self > other) {
            (true, _, _) => Some(Equal),
            (_, true, _) => Some(Less),
            (_, _, true) => Some(Greater),
            _ => None,
        }
    }
    #[inline]
    fn lt(&self, other: &Self) -> bool {
        self.cmplt(*other).all()
    }
    #[inline]
    fn le(&self, other: &Self) -> bool {
        self.cmple(*other).all()
    }
    #[inline]
    fn gt(&self, other: &Self) -> bool {
        self.cmpgt(*other).all()
    }
    #[inline]
    fn ge(&self, other: &Self) -> bool {
        self.cmpge(*other).all()
    }
}
vector_ops!(Vec3<f32>, f32, Vec3<u32>, arith, neg);
vector_math!(Vec3<f32>, f32, ord, float);
impl Vec3<f32> {
    /// The cross product, perpendicular to both.
    #[inline]
    pub fn cross(self, rhs: Self) -> Self {
        vec3(
            self.y * rhs.z - rhs.y * self.z,
            self.z * rhs.x - rhs.z * self.x,
            self.x * rhs.y - rhs.x * self.y,
        )
    }
}

impl Vec3<i32> {
    /// Lane-wise `<`.
    #[inline]
    pub fn cmplt(self, rhs: Self) -> Vec3<bool> {
        self.zip_lanes(rhs, |a, b| a < b)
    }

    /// Lane-wise `<=`.
    #[inline]
    pub fn cmple(self, rhs: Self) -> Vec3<bool> {
        self.zip_lanes(rhs, |a, b| a <= b)
    }

    /// Lane-wise `>`.
    #[inline]
    pub fn cmpgt(self, rhs: Self) -> Vec3<bool> {
        self.zip_lanes(rhs, |a, b| a > b)
    }

    /// Lane-wise `>=`.
    #[inline]
    pub fn cmpge(self, rhs: Self) -> Vec3<bool> {
        self.zip_lanes(rhs, |a, b| a >= b)
    }
}
/// `a < b` when every lane is, as `a.cmplt(b).all()`, and so for `<=`, `>`
/// and `>=`. `partial_cmp` is `Equal`, `Less` or `Greater` when every lane
/// agrees, and `None` otherwise. So `a <= b` holds more often than
/// `a < b || a == b`, which `PartialOrd` asks of it, as it does in nalgebra.
impl PartialOrd for Vec3<i32> {
    #[inline]
    fn partial_cmp(&self, other: &Self) -> Option<core::cmp::Ordering> {
        use core::cmp::Ordering::*;
        match (self == other, self < other, self > other) {
            (true, _, _) => Some(Equal),
            (_, true, _) => Some(Less),
            (_, _, true) => Some(Greater),
            _ => None,
        }
    }
    #[inline]
    fn lt(&self, other: &Self) -> bool {
        self.cmplt(*other).all()
    }
    #[inline]
    fn le(&self, other: &Self) -> bool {
        self.cmple(*other).all()
    }
    #[inline]
    fn gt(&self, other: &Self) -> bool {
        self.cmpgt(*other).all()
    }
    #[inline]
    fn ge(&self, other: &Self) -> bool {
        self.cmpge(*other).all()
    }
}
vector_ops!(Vec3<i32>, i32, Vec3<u32>, arith, bitwise, shift, neg, not);
vector_math!(Vec3<i32>, i32, ord, signed, wrapping);

impl Vec3<u32> {
    /// Lane-wise `<`.
    #[inline]
    pub fn cmplt(self, rhs: Self) -> Vec3<bool> {
        self.zip_lanes(rhs, |a, b| a < b)
    }

    /// Lane-wise `<=`.
    #[inline]
    pub fn cmple(self, rhs: Self) -> Vec3<bool> {
        self.zip_lanes(rhs, |a, b| a <= b)
    }

    /// Lane-wise `>`.
    #[inline]
    pub fn cmpgt(self, rhs: Self) -> Vec3<bool> {
        self.zip_lanes(rhs, |a, b| a > b)
    }

    /// Lane-wise `>=`.
    #[inline]
    pub fn cmpge(self, rhs: Self) -> Vec3<bool> {
        self.zip_lanes(rhs, |a, b| a >= b)
    }
}
/// `a < b` when every lane is, as `a.cmplt(b).all()`, and so for `<=`, `>`
/// and `>=`. `partial_cmp` is `Equal`, `Less` or `Greater` when every lane
/// agrees, and `None` otherwise. So `a <= b` holds more often than
/// `a < b || a == b`, which `PartialOrd` asks of it, as it does in nalgebra.
impl PartialOrd for Vec3<u32> {
    #[inline]
    fn partial_cmp(&self, other: &Self) -> Option<core::cmp::Ordering> {
        use core::cmp::Ordering::*;
        match (self == other, self < other, self > other) {
            (true, _, _) => Some(Equal),
            (_, true, _) => Some(Less),
            (_, _, true) => Some(Greater),
            _ => None,
        }
    }
    #[inline]
    fn lt(&self, other: &Self) -> bool {
        self.cmplt(*other).all()
    }
    #[inline]
    fn le(&self, other: &Self) -> bool {
        self.cmple(*other).all()
    }
    #[inline]
    fn gt(&self, other: &Self) -> bool {
        self.cmpgt(*other).all()
    }
    #[inline]
    fn ge(&self, other: &Self) -> bool {
        self.cmpge(*other).all()
    }
}
vector_ops!(Vec3<u32>, u32, Vec3<u32>, arith, bitwise, shift, not);
vector_math!(Vec3<u32>, u32, ord, wrapping);

vector_ops!(Vec3<bool>, bool, Vec3<u32>, bitwise, not);
vector_math!(Vec3<bool>, bool, bool);

/// `vec4<T>` in WGSL. A bare `Vec4` is `Vec4<f32>`, WGSL's `vec4f`.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
#[repr(C)]
pub struct Vec4<T = f32> {
    pub x: T,
    pub y: T,
    pub z: T,
    pub w: T,
}

/// Build a [`Vec4`] from its components.
#[inline]
pub const fn vec4<T: Scalar>(x: T, y: T, z: T, w: T) -> Vec4<T> {
    Vec4 { x, y, z, w }
}

impl<T: Scalar> Vec4<T> {
    pub const ZERO: Self = vec4(T::ZERO, T::ZERO, T::ZERO, T::ZERO);
    pub const ONE: Self = vec4(T::ONE, T::ONE, T::ONE, T::ONE);

    /// Every lane set to `v`.
    #[inline]
    pub const fn splat(v: T) -> Self {
        vec4(v, v, v, v)
    }

    /// Each lane converted to `U`, as `as` converts a scalar: `v.cast::<i32>()`
    /// is WGSL's `vec4<i32>(v)`. Into `bool`, a lane is `true` unless it is zero.
    #[inline]
    pub fn cast<U: Scalar>(self) -> Vec4<U> {
        self.map_lanes(U::convert)
    }

    /// `f` of each lane.
    #[inline]
    pub(crate) fn map_lanes<U: Scalar>(self, f: impl Fn(T) -> U) -> Vec4<U> {
        vec4(f(self.x), f(self.y), f(self.z), f(self.w))
    }

    /// `f` of each pair of lanes.
    #[inline]
    pub(crate) fn zip_lanes<U: Scalar, V: Scalar>(
        self,
        rhs: Vec4<U>,
        f: impl Fn(T, U) -> V,
    ) -> Vec4<V> {
        vec4(
            f(self.x, rhs.x),
            f(self.y, rhs.y),
            f(self.z, rhs.z),
            f(self.w, rhs.w),
        )
    }

    /// `f` of each three lanes.
    #[inline]
    pub(crate) fn zip3_lanes(self, b: Self, c: Self, f: impl Fn(T, T, T) -> T) -> Self {
        vec4(
            f(self.x, b.x, c.x),
            f(self.y, b.y, c.y),
            f(self.z, b.z, c.z),
            f(self.w, b.w, c.w),
        )
    }

    /// The lanes, combined first to last.
    #[inline]
    pub(crate) fn reduce_lanes(self, f: impl Fn(T, T) -> T) -> T {
        f(f(f(self.x, self.y), self.z), self.w)
    }

    /// One lane narrower, dropping the last.
    #[inline]
    pub const fn truncate(self) -> Vec3<T> {
        vec3(self.x, self.y, self.z)
    }

    /// Lane-wise `==`.
    #[inline]
    pub fn cmpeq(self, rhs: Self) -> Vec4<bool> {
        self.zip_lanes(rhs, |a, b| a == b)
    }

    /// Lane-wise `!=`.
    #[inline]
    pub fn cmpne(self, rhs: Self) -> Vec4<bool> {
        self.zip_lanes(rhs, |a, b| a != b)
    }

    #[inline]
    pub const fn xy(self) -> Vec2<T> {
        vec2(self.x, self.y)
    }

    #[inline]
    pub const fn xz(self) -> Vec2<T> {
        vec2(self.x, self.z)
    }

    #[inline]
    pub const fn xw(self) -> Vec2<T> {
        vec2(self.x, self.w)
    }

    #[inline]
    pub const fn yx(self) -> Vec2<T> {
        vec2(self.y, self.x)
    }

    #[inline]
    pub const fn yz(self) -> Vec2<T> {
        vec2(self.y, self.z)
    }

    #[inline]
    pub const fn yw(self) -> Vec2<T> {
        vec2(self.y, self.w)
    }

    #[inline]
    pub const fn zx(self) -> Vec2<T> {
        vec2(self.z, self.x)
    }

    #[inline]
    pub const fn zy(self) -> Vec2<T> {
        vec2(self.z, self.y)
    }

    #[inline]
    pub const fn zw(self) -> Vec2<T> {
        vec2(self.z, self.w)
    }

    #[inline]
    pub const fn wx(self) -> Vec2<T> {
        vec2(self.w, self.x)
    }

    #[inline]
    pub const fn wy(self) -> Vec2<T> {
        vec2(self.w, self.y)
    }

    #[inline]
    pub const fn wz(self) -> Vec2<T> {
        vec2(self.w, self.z)
    }

    #[inline]
    pub const fn xyz(self) -> Vec3<T> {
        vec3(self.x, self.y, self.z)
    }

    #[inline]
    pub const fn xyw(self) -> Vec3<T> {
        vec3(self.x, self.y, self.w)
    }

    #[inline]
    pub const fn xzy(self) -> Vec3<T> {
        vec3(self.x, self.z, self.y)
    }

    #[inline]
    pub const fn xzw(self) -> Vec3<T> {
        vec3(self.x, self.z, self.w)
    }

    #[inline]
    pub const fn xwy(self) -> Vec3<T> {
        vec3(self.x, self.w, self.y)
    }

    #[inline]
    pub const fn xwz(self) -> Vec3<T> {
        vec3(self.x, self.w, self.z)
    }

    #[inline]
    pub const fn yxz(self) -> Vec3<T> {
        vec3(self.y, self.x, self.z)
    }

    #[inline]
    pub const fn yxw(self) -> Vec3<T> {
        vec3(self.y, self.x, self.w)
    }

    #[inline]
    pub const fn yzx(self) -> Vec3<T> {
        vec3(self.y, self.z, self.x)
    }

    #[inline]
    pub const fn yzw(self) -> Vec3<T> {
        vec3(self.y, self.z, self.w)
    }

    #[inline]
    pub const fn ywx(self) -> Vec3<T> {
        vec3(self.y, self.w, self.x)
    }

    #[inline]
    pub const fn ywz(self) -> Vec3<T> {
        vec3(self.y, self.w, self.z)
    }

    #[inline]
    pub const fn zxy(self) -> Vec3<T> {
        vec3(self.z, self.x, self.y)
    }

    #[inline]
    pub const fn zxw(self) -> Vec3<T> {
        vec3(self.z, self.x, self.w)
    }

    #[inline]
    pub const fn zyx(self) -> Vec3<T> {
        vec3(self.z, self.y, self.x)
    }

    #[inline]
    pub const fn zyw(self) -> Vec3<T> {
        vec3(self.z, self.y, self.w)
    }

    #[inline]
    pub const fn zwx(self) -> Vec3<T> {
        vec3(self.z, self.w, self.x)
    }

    #[inline]
    pub const fn zwy(self) -> Vec3<T> {
        vec3(self.z, self.w, self.y)
    }

    #[inline]
    pub const fn wxy(self) -> Vec3<T> {
        vec3(self.w, self.x, self.y)
    }

    #[inline]
    pub const fn wxz(self) -> Vec3<T> {
        vec3(self.w, self.x, self.z)
    }

    #[inline]
    pub const fn wyx(self) -> Vec3<T> {
        vec3(self.w, self.y, self.x)
    }

    #[inline]
    pub const fn wyz(self) -> Vec3<T> {
        vec3(self.w, self.y, self.z)
    }

    #[inline]
    pub const fn wzx(self) -> Vec3<T> {
        vec3(self.w, self.z, self.x)
    }

    #[inline]
    pub const fn wzy(self) -> Vec3<T> {
        vec3(self.w, self.z, self.y)
    }

    #[inline]
    pub const fn xyzw(self) -> Vec4<T> {
        vec4(self.x, self.y, self.z, self.w)
    }

    #[inline]
    pub const fn xywz(self) -> Vec4<T> {
        vec4(self.x, self.y, self.w, self.z)
    }

    #[inline]
    pub const fn xzyw(self) -> Vec4<T> {
        vec4(self.x, self.z, self.y, self.w)
    }

    #[inline]
    pub const fn xzwy(self) -> Vec4<T> {
        vec4(self.x, self.z, self.w, self.y)
    }

    #[inline]
    pub const fn xwyz(self) -> Vec4<T> {
        vec4(self.x, self.w, self.y, self.z)
    }

    #[inline]
    pub const fn xwzy(self) -> Vec4<T> {
        vec4(self.x, self.w, self.z, self.y)
    }

    #[inline]
    pub const fn yxzw(self) -> Vec4<T> {
        vec4(self.y, self.x, self.z, self.w)
    }

    #[inline]
    pub const fn yxwz(self) -> Vec4<T> {
        vec4(self.y, self.x, self.w, self.z)
    }

    #[inline]
    pub const fn yzxw(self) -> Vec4<T> {
        vec4(self.y, self.z, self.x, self.w)
    }

    #[inline]
    pub const fn yzwx(self) -> Vec4<T> {
        vec4(self.y, self.z, self.w, self.x)
    }

    #[inline]
    pub const fn ywxz(self) -> Vec4<T> {
        vec4(self.y, self.w, self.x, self.z)
    }

    #[inline]
    pub const fn ywzx(self) -> Vec4<T> {
        vec4(self.y, self.w, self.z, self.x)
    }

    #[inline]
    pub const fn zxyw(self) -> Vec4<T> {
        vec4(self.z, self.x, self.y, self.w)
    }

    #[inline]
    pub const fn zxwy(self) -> Vec4<T> {
        vec4(self.z, self.x, self.w, self.y)
    }

    #[inline]
    pub const fn zyxw(self) -> Vec4<T> {
        vec4(self.z, self.y, self.x, self.w)
    }

    #[inline]
    pub const fn zywx(self) -> Vec4<T> {
        vec4(self.z, self.y, self.w, self.x)
    }

    #[inline]
    pub const fn zwxy(self) -> Vec4<T> {
        vec4(self.z, self.w, self.x, self.y)
    }

    #[inline]
    pub const fn zwyx(self) -> Vec4<T> {
        vec4(self.z, self.w, self.y, self.x)
    }

    #[inline]
    pub const fn wxyz(self) -> Vec4<T> {
        vec4(self.w, self.x, self.y, self.z)
    }

    #[inline]
    pub const fn wxzy(self) -> Vec4<T> {
        vec4(self.w, self.x, self.z, self.y)
    }

    #[inline]
    pub const fn wyxz(self) -> Vec4<T> {
        vec4(self.w, self.y, self.x, self.z)
    }

    #[inline]
    pub const fn wyzx(self) -> Vec4<T> {
        vec4(self.w, self.y, self.z, self.x)
    }

    #[inline]
    pub const fn wzxy(self) -> Vec4<T> {
        vec4(self.w, self.z, self.x, self.y)
    }

    #[inline]
    pub const fn wzyx(self) -> Vec4<T> {
        vec4(self.w, self.z, self.y, self.x)
    }

    #[inline]
    pub const fn r(self) -> T {
        self.x
    }

    #[inline]
    pub const fn g(self) -> T {
        self.y
    }

    #[inline]
    pub const fn b(self) -> T {
        self.z
    }

    #[inline]
    pub const fn a(self) -> T {
        self.w
    }

    #[inline]
    pub const fn rg(self) -> Vec2<T> {
        vec2(self.x, self.y)
    }

    #[inline]
    pub const fn gr(self) -> Vec2<T> {
        vec2(self.y, self.x)
    }

    #[inline]
    pub const fn ba(self) -> Vec2<T> {
        vec2(self.z, self.w)
    }

    #[inline]
    pub const fn rgb(self) -> Vec3<T> {
        vec3(self.x, self.y, self.z)
    }

    #[inline]
    pub const fn rgba(self) -> Vec4<T> {
        vec4(self.x, self.y, self.z, self.w)
    }
}

impl<T: Scalar> Index<usize> for Vec4<T> {
    type Output = T;
    #[inline]
    fn index(&self, index: usize) -> &T {
        match index {
            0 => &self.x,
            1 => &self.y,
            2 => &self.z,
            3 => &self.w,
            _ => panic!("lane {index} of a Vec4"),
        }
    }
}
impl<T: Scalar> IndexMut<usize> for Vec4<T> {
    #[inline]
    fn index_mut(&mut self, index: usize) -> &mut T {
        match index {
            0 => &mut self.x,
            1 => &mut self.y,
            2 => &mut self.z,
            3 => &mut self.w,
            _ => panic!("lane {index} of a Vec4"),
        }
    }
}
impl<T: Scalar> From<(Vec2<T>, Vec2<T>)> for Vec4<T> {
    #[inline]
    fn from((a, b): (Vec2<T>, Vec2<T>)) -> Self {
        vec4(a.x, a.y, b.x, b.y)
    }
}

impl Vec4<f32> {
    /// Lane-wise `<`.
    #[inline]
    pub fn cmplt(self, rhs: Self) -> Vec4<bool> {
        self.zip_lanes(rhs, |a, b| a < b)
    }

    /// Lane-wise `<=`.
    #[inline]
    pub fn cmple(self, rhs: Self) -> Vec4<bool> {
        self.zip_lanes(rhs, |a, b| a <= b)
    }

    /// Lane-wise `>`.
    #[inline]
    pub fn cmpgt(self, rhs: Self) -> Vec4<bool> {
        self.zip_lanes(rhs, |a, b| a > b)
    }

    /// Lane-wise `>=`.
    #[inline]
    pub fn cmpge(self, rhs: Self) -> Vec4<bool> {
        self.zip_lanes(rhs, |a, b| a >= b)
    }
}
/// `a < b` when every lane is, as `a.cmplt(b).all()`, and so for `<=`, `>`
/// and `>=`. `partial_cmp` is `Equal`, `Less` or `Greater` when every lane
/// agrees, and `None` otherwise. So `a <= b` holds more often than
/// `a < b || a == b`, which `PartialOrd` asks of it, as it does in nalgebra.
impl PartialOrd for Vec4<f32> {
    #[inline]
    fn partial_cmp(&self, other: &Self) -> Option<core::cmp::Ordering> {
        use core::cmp::Ordering::*;
        match (self == other, self < other, self > other) {
            (true, _, _) => Some(Equal),
            (_, true, _) => Some(Less),
            (_, _, true) => Some(Greater),
            _ => None,
        }
    }
    #[inline]
    fn lt(&self, other: &Self) -> bool {
        self.cmplt(*other).all()
    }
    #[inline]
    fn le(&self, other: &Self) -> bool {
        self.cmple(*other).all()
    }
    #[inline]
    fn gt(&self, other: &Self) -> bool {
        self.cmpgt(*other).all()
    }
    #[inline]
    fn ge(&self, other: &Self) -> bool {
        self.cmpge(*other).all()
    }
}
vector_ops!(Vec4<f32>, f32, Vec4<u32>, arith, neg);
vector_math!(Vec4<f32>, f32, ord, float);

impl Vec4<i32> {
    /// Lane-wise `<`.
    #[inline]
    pub fn cmplt(self, rhs: Self) -> Vec4<bool> {
        self.zip_lanes(rhs, |a, b| a < b)
    }

    /// Lane-wise `<=`.
    #[inline]
    pub fn cmple(self, rhs: Self) -> Vec4<bool> {
        self.zip_lanes(rhs, |a, b| a <= b)
    }

    /// Lane-wise `>`.
    #[inline]
    pub fn cmpgt(self, rhs: Self) -> Vec4<bool> {
        self.zip_lanes(rhs, |a, b| a > b)
    }

    /// Lane-wise `>=`.
    #[inline]
    pub fn cmpge(self, rhs: Self) -> Vec4<bool> {
        self.zip_lanes(rhs, |a, b| a >= b)
    }
}
/// `a < b` when every lane is, as `a.cmplt(b).all()`, and so for `<=`, `>`
/// and `>=`. `partial_cmp` is `Equal`, `Less` or `Greater` when every lane
/// agrees, and `None` otherwise. So `a <= b` holds more often than
/// `a < b || a == b`, which `PartialOrd` asks of it, as it does in nalgebra.
impl PartialOrd for Vec4<i32> {
    #[inline]
    fn partial_cmp(&self, other: &Self) -> Option<core::cmp::Ordering> {
        use core::cmp::Ordering::*;
        match (self == other, self < other, self > other) {
            (true, _, _) => Some(Equal),
            (_, true, _) => Some(Less),
            (_, _, true) => Some(Greater),
            _ => None,
        }
    }
    #[inline]
    fn lt(&self, other: &Self) -> bool {
        self.cmplt(*other).all()
    }
    #[inline]
    fn le(&self, other: &Self) -> bool {
        self.cmple(*other).all()
    }
    #[inline]
    fn gt(&self, other: &Self) -> bool {
        self.cmpgt(*other).all()
    }
    #[inline]
    fn ge(&self, other: &Self) -> bool {
        self.cmpge(*other).all()
    }
}
vector_ops!(Vec4<i32>, i32, Vec4<u32>, arith, bitwise, shift, neg, not);
vector_math!(Vec4<i32>, i32, ord, signed, wrapping);

impl Vec4<u32> {
    /// Lane-wise `<`.
    #[inline]
    pub fn cmplt(self, rhs: Self) -> Vec4<bool> {
        self.zip_lanes(rhs, |a, b| a < b)
    }

    /// Lane-wise `<=`.
    #[inline]
    pub fn cmple(self, rhs: Self) -> Vec4<bool> {
        self.zip_lanes(rhs, |a, b| a <= b)
    }

    /// Lane-wise `>`.
    #[inline]
    pub fn cmpgt(self, rhs: Self) -> Vec4<bool> {
        self.zip_lanes(rhs, |a, b| a > b)
    }

    /// Lane-wise `>=`.
    #[inline]
    pub fn cmpge(self, rhs: Self) -> Vec4<bool> {
        self.zip_lanes(rhs, |a, b| a >= b)
    }
}
/// `a < b` when every lane is, as `a.cmplt(b).all()`, and so for `<=`, `>`
/// and `>=`. `partial_cmp` is `Equal`, `Less` or `Greater` when every lane
/// agrees, and `None` otherwise. So `a <= b` holds more often than
/// `a < b || a == b`, which `PartialOrd` asks of it, as it does in nalgebra.
impl PartialOrd for Vec4<u32> {
    #[inline]
    fn partial_cmp(&self, other: &Self) -> Option<core::cmp::Ordering> {
        use core::cmp::Ordering::*;
        match (self == other, self < other, self > other) {
            (true, _, _) => Some(Equal),
            (_, true, _) => Some(Less),
            (_, _, true) => Some(Greater),
            _ => None,
        }
    }
    #[inline]
    fn lt(&self, other: &Self) -> bool {
        self.cmplt(*other).all()
    }
    #[inline]
    fn le(&self, other: &Self) -> bool {
        self.cmple(*other).all()
    }
    #[inline]
    fn gt(&self, other: &Self) -> bool {
        self.cmpgt(*other).all()
    }
    #[inline]
    fn ge(&self, other: &Self) -> bool {
        self.cmpge(*other).all()
    }
}
vector_ops!(Vec4<u32>, u32, Vec4<u32>, arith, bitwise, shift, not);
vector_math!(Vec4<u32>, u32, ord, wrapping);

vector_ops!(Vec4<bool>, bool, Vec4<u32>, bitwise, not);
vector_math!(Vec4<bool>, bool, bool);

impl<T: Scalar> From<[T; 2]> for Vec2<T> {
    #[inline]
    fn from([x, y]: [T; 2]) -> Self {
        Vec2 { x, y }
    }
}
impl<T: Scalar> From<Vec2<T>> for [T; 2] {
    #[inline]
    fn from(v: Vec2<T>) -> Self {
        [v.x, v.y]
    }
}
#[cfg(feature = "mint")]
impl<T: Scalar> From<mint::Vector2<T>> for Vec2<T> {
    #[inline]
    fn from(v: mint::Vector2<T>) -> Self {
        Vec2 { x: v.x, y: v.y }
    }
}
#[cfg(feature = "mint")]
impl<T: Scalar> From<Vec2<T>> for mint::Vector2<T> {
    #[inline]
    fn from(v: Vec2<T>) -> Self {
        mint::Vector2 { x: v.x, y: v.y }
    }
}
// Names the mint type, for a crate that takes any math library's vectors,
// such as one that picks a vertex format for a field.
#[cfg(feature = "mint")]
impl<T: Scalar> mint::IntoMint for Vec2<T> {
    type MintType = mint::Vector2<T>;
}
// SAFETY: `#[repr(C)]` lanes of one type, so there is no padding, and
// all zeroes, like any bytes of a `Pod` lane type, are valid lanes.
#[cfg(feature = "bytemuck")]
unsafe impl<T: Scalar + bytemuck::Zeroable> bytemuck::Zeroable for Vec2<T> {}
#[cfg(feature = "bytemuck")]
unsafe impl<T: Scalar + bytemuck::Pod> bytemuck::Pod for Vec2<T> {}
impl<T: Scalar> From<[T; 3]> for Vec3<T> {
    #[inline]
    fn from([x, y, z]: [T; 3]) -> Self {
        Vec3 { x, y, z }
    }
}
impl<T: Scalar> From<Vec3<T>> for [T; 3] {
    #[inline]
    fn from(v: Vec3<T>) -> Self {
        [v.x, v.y, v.z]
    }
}
#[cfg(feature = "mint")]
impl<T: Scalar> From<mint::Vector3<T>> for Vec3<T> {
    #[inline]
    fn from(v: mint::Vector3<T>) -> Self {
        Vec3 {
            x: v.x,
            y: v.y,
            z: v.z,
        }
    }
}
#[cfg(feature = "mint")]
impl<T: Scalar> From<Vec3<T>> for mint::Vector3<T> {
    #[inline]
    fn from(v: Vec3<T>) -> Self {
        mint::Vector3 {
            x: v.x,
            y: v.y,
            z: v.z,
        }
    }
}
// Names the mint type, for a crate that takes any math library's vectors,
// such as one that picks a vertex format for a field.
#[cfg(feature = "mint")]
impl<T: Scalar> mint::IntoMint for Vec3<T> {
    type MintType = mint::Vector3<T>;
}
// SAFETY: `#[repr(C)]` lanes of one type, so there is no padding, and
// all zeroes, like any bytes of a `Pod` lane type, are valid lanes.
#[cfg(feature = "bytemuck")]
unsafe impl<T: Scalar + bytemuck::Zeroable> bytemuck::Zeroable for Vec3<T> {}
#[cfg(feature = "bytemuck")]
unsafe impl<T: Scalar + bytemuck::Pod> bytemuck::Pod for Vec3<T> {}
impl<T: Scalar> From<[T; 4]> for Vec4<T> {
    #[inline]
    fn from([x, y, z, w]: [T; 4]) -> Self {
        Vec4 { x, y, z, w }
    }
}
impl<T: Scalar> From<Vec4<T>> for [T; 4] {
    #[inline]
    fn from(v: Vec4<T>) -> Self {
        [v.x, v.y, v.z, v.w]
    }
}
#[cfg(feature = "mint")]
impl<T: Scalar> From<mint::Vector4<T>> for Vec4<T> {
    #[inline]
    fn from(v: mint::Vector4<T>) -> Self {
        Vec4 {
            x: v.x,
            y: v.y,
            z: v.z,
            w: v.w,
        }
    }
}
#[cfg(feature = "mint")]
impl<T: Scalar> From<mint::Quaternion<T>> for Vec4<T> {
    /// `xyz` is the vector part and `w` the scalar, as a shader keeps one.
    #[inline]
    fn from(q: mint::Quaternion<T>) -> Self {
        Vec4 {
            x: q.v.x,
            y: q.v.y,
            z: q.v.z,
            w: q.s,
        }
    }
}
#[cfg(feature = "mint")]
impl<T: Scalar> From<Vec4<T>> for mint::Vector4<T> {
    #[inline]
    fn from(v: Vec4<T>) -> Self {
        mint::Vector4 {
            x: v.x,
            y: v.y,
            z: v.z,
            w: v.w,
        }
    }
}
// Names the mint type, for a crate that takes any math library's vectors,
// such as one that picks a vertex format for a field.
#[cfg(feature = "mint")]
impl<T: Scalar> mint::IntoMint for Vec4<T> {
    type MintType = mint::Vector4<T>;
}
// SAFETY: `#[repr(C)]` lanes of one type, so there is no padding, and
// all zeroes, like any bytes of a `Pod` lane type, are valid lanes.
#[cfg(feature = "bytemuck")]
unsafe impl<T: Scalar + bytemuck::Zeroable> bytemuck::Zeroable for Vec4<T> {}
#[cfg(feature = "bytemuck")]
unsafe impl<T: Scalar + bytemuck::Pod> bytemuck::Pod for Vec4<T> {}

impl From<Vec2<f32>> for Vec2<i32> {
    #[inline]
    fn from(v: Vec2<f32>) -> Self {
        v.cast()
    }
}
impl From<Vec2<f32>> for Vec2<u32> {
    #[inline]
    fn from(v: Vec2<f32>) -> Self {
        v.cast()
    }
}
impl From<Vec2<f32>> for Vec2<bool> {
    #[inline]
    fn from(v: Vec2<f32>) -> Self {
        v.cast()
    }
}
impl From<Vec2<i32>> for Vec2<f32> {
    #[inline]
    fn from(v: Vec2<i32>) -> Self {
        v.cast()
    }
}
impl From<Vec2<i32>> for Vec2<u32> {
    #[inline]
    fn from(v: Vec2<i32>) -> Self {
        v.cast()
    }
}
impl From<Vec2<i32>> for Vec2<bool> {
    #[inline]
    fn from(v: Vec2<i32>) -> Self {
        v.cast()
    }
}
impl From<Vec2<u32>> for Vec2<f32> {
    #[inline]
    fn from(v: Vec2<u32>) -> Self {
        v.cast()
    }
}
impl From<Vec2<u32>> for Vec2<i32> {
    #[inline]
    fn from(v: Vec2<u32>) -> Self {
        v.cast()
    }
}
impl From<Vec2<u32>> for Vec2<bool> {
    #[inline]
    fn from(v: Vec2<u32>) -> Self {
        v.cast()
    }
}
impl From<Vec2<bool>> for Vec2<f32> {
    #[inline]
    fn from(v: Vec2<bool>) -> Self {
        v.cast()
    }
}
impl From<Vec2<bool>> for Vec2<i32> {
    #[inline]
    fn from(v: Vec2<bool>) -> Self {
        v.cast()
    }
}
impl From<Vec2<bool>> for Vec2<u32> {
    #[inline]
    fn from(v: Vec2<bool>) -> Self {
        v.cast()
    }
}
impl From<Vec3<f32>> for Vec3<i32> {
    #[inline]
    fn from(v: Vec3<f32>) -> Self {
        v.cast()
    }
}
impl From<Vec3<f32>> for Vec3<u32> {
    #[inline]
    fn from(v: Vec3<f32>) -> Self {
        v.cast()
    }
}
impl From<Vec3<f32>> for Vec3<bool> {
    #[inline]
    fn from(v: Vec3<f32>) -> Self {
        v.cast()
    }
}
impl From<Vec3<i32>> for Vec3<f32> {
    #[inline]
    fn from(v: Vec3<i32>) -> Self {
        v.cast()
    }
}
impl From<Vec3<i32>> for Vec3<u32> {
    #[inline]
    fn from(v: Vec3<i32>) -> Self {
        v.cast()
    }
}
impl From<Vec3<i32>> for Vec3<bool> {
    #[inline]
    fn from(v: Vec3<i32>) -> Self {
        v.cast()
    }
}
impl From<Vec3<u32>> for Vec3<f32> {
    #[inline]
    fn from(v: Vec3<u32>) -> Self {
        v.cast()
    }
}
impl From<Vec3<u32>> for Vec3<i32> {
    #[inline]
    fn from(v: Vec3<u32>) -> Self {
        v.cast()
    }
}
impl From<Vec3<u32>> for Vec3<bool> {
    #[inline]
    fn from(v: Vec3<u32>) -> Self {
        v.cast()
    }
}
impl From<Vec3<bool>> for Vec3<f32> {
    #[inline]
    fn from(v: Vec3<bool>) -> Self {
        v.cast()
    }
}
impl From<Vec3<bool>> for Vec3<i32> {
    #[inline]
    fn from(v: Vec3<bool>) -> Self {
        v.cast()
    }
}
impl From<Vec3<bool>> for Vec3<u32> {
    #[inline]
    fn from(v: Vec3<bool>) -> Self {
        v.cast()
    }
}
impl From<Vec4<f32>> for Vec4<i32> {
    #[inline]
    fn from(v: Vec4<f32>) -> Self {
        v.cast()
    }
}
impl From<Vec4<f32>> for Vec4<u32> {
    #[inline]
    fn from(v: Vec4<f32>) -> Self {
        v.cast()
    }
}
impl From<Vec4<f32>> for Vec4<bool> {
    #[inline]
    fn from(v: Vec4<f32>) -> Self {
        v.cast()
    }
}
impl From<Vec4<i32>> for Vec4<f32> {
    #[inline]
    fn from(v: Vec4<i32>) -> Self {
        v.cast()
    }
}
impl From<Vec4<i32>> for Vec4<u32> {
    #[inline]
    fn from(v: Vec4<i32>) -> Self {
        v.cast()
    }
}
impl From<Vec4<i32>> for Vec4<bool> {
    #[inline]
    fn from(v: Vec4<i32>) -> Self {
        v.cast()
    }
}
impl From<Vec4<u32>> for Vec4<f32> {
    #[inline]
    fn from(v: Vec4<u32>) -> Self {
        v.cast()
    }
}
impl From<Vec4<u32>> for Vec4<i32> {
    #[inline]
    fn from(v: Vec4<u32>) -> Self {
        v.cast()
    }
}
impl From<Vec4<u32>> for Vec4<bool> {
    #[inline]
    fn from(v: Vec4<u32>) -> Self {
        v.cast()
    }
}
impl From<Vec4<bool>> for Vec4<f32> {
    #[inline]
    fn from(v: Vec4<bool>) -> Self {
        v.cast()
    }
}
impl From<Vec4<bool>> for Vec4<i32> {
    #[inline]
    fn from(v: Vec4<bool>) -> Self {
        v.cast()
    }
}
impl From<Vec4<bool>> for Vec4<u32> {
    #[inline]
    fn from(v: Vec4<bool>) -> Self {
        v.cast()
    }
}
